### ISSUE TITLE
curator_cli way to specify continue_if_exception?

### ISSUE THREAD

**Issue by pfremm** [elastic/curator#1000]
I am using curator_cli and am looking to ignore exception in the case if an index doesn't exist when running delete_indices.  I cannot seem to find if that's supported.

**Comment by untergeek** [comment]
That flag does not exist with `curator_cli` as it only performs one action.  If you're at the cli, you determine whether you want to run another action or not.

**Comment by pfremm** [comment]
My issue is we have a batch job to cleanup old indices as we use ES for aggregated logging.  If no indices exist to cleanup right now curator_cli throws and exception and the exit code is not zero.  Am I missing something to exit with a 0 exit code if no indices exist for my filters?

**Comment by untergeek** [comment]
And you're obliged/forced to use `curator_cli` rather than regular Curator?  Because, as you've discovered, there is no way to exit with a 0 exit code with `curator_cli` unless it exited cleanly.

A potential work-around would be to use `show_indices` with the same `--filter_list` _before_ you run the `delete_indices` command.  If no indices show up, then you can skip running that particular command, avoiding a non-zero exit code from the _actual_ call you want to make.  Just don't test for one on the `show_indices` command, either:

```
root@esclient:~# curator_cli  show_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"ipmi"}'
ipmi-000002
root@esclient:~# echo $?
0
root@esclient:~# curator_cli  show_indices --filter_list '{"filtertype":"pattern","kind":"prefix","value":"ugly"}'
root@esclient:~# echo $?
1
```

**Comment by pfremm** [comment]
I thought the CLI was going to be easier since I was using env variables.  Just saw https://www.elastic.co/guide/en/elasticsearch/client/curator/5.1/envvars.html.  I guess I can specify them in config files too.

**Comment by untergeek** [comment]
Yes, indeed!  Feel free to close this issue if that satisfies you.
