### ISSUE TITLE
Support running in serverless architectures

### ISSUE THREAD

**Issue by dmcd** [elastic/curator#1031]
I would like to run curator from an AWS lambda function but can't see how I can invoke the cli from source in this way.

**Comment by untergeek** [comment]
https://www.elastic.co/blog/serverless-elasticsearch-curator-on-aws-lambda

As this is a usage question, please ask follow-up questions at https://discuss.elastic.co

**Comment by dmcd** [comment]
The problem I'm having is that curator uses the click package which stops me from being able to pass in parameters from my handler function (https://github.com/pallets/click/issues/40). 

I've worked around this issue by taking a copy of the source for curator and commenting out the click attributes on the cli function:

``` python
# @click.command()
# @click.option('--config',
#     help="Path to configuration file. Default: ~/.curator/curator.yml",
#     type=click.Path(exists=True), default=settings.config_file()
# )
# @click.option('--dry-run', is_flag=True, help='Do not perform any changes.')
# @click.argument('action_file', type=click.Path(exists=True), nargs=1)
# @click.version_option(version=__version__)
def cli(config, dry_run, action_file):
```
This allows me to invoke curator from my handler function:

``` python
#!/usr/bin/env python

from curator.cli import cli

def run(event, context):
    cli('curator.yml', False, 'actions.yml')
```

**Comment by untergeek** [comment]
I think you're missing the point of using Curator with the Lambda architecture.  You're not supposed to use the Click API, which is exclusively for a CLI interface, with Lambda architecture.  I think the blog post does a pretty good job of explaining how to do it the right way.  You're supposed to use the Curator API, rather than the CLI interface.  There are ways of doing so programmatically (that's how the `cli` function behaves).

You're effectively trying to run an interactive program in a non-interactive environment.  You were never meant to pass things to the `cli` function this way.  Since you've created your own work-around to this, you're welcome to continue doing so, but will likely have to go through the same hoops with every future release of Curator.

**Comment by dmcd** [comment]
Thanks @untergeek. I understand that I'm not following the intended usage, sorry about that. However, I really like the CLI interface because it allows me to ignore the underlying implementation and focus on the config. If I'm not mistaken, the blog post you referenced suggests hand writing some of the functionality that you get for free with the CLI interface. It seems I would need to reimplement quite a large block of code to achieve the same flexibility that the CLI offers. Where as, the above modifications allow me to get up and running quickly and it is working flawlessly so far. 

But I agree, it means I need to bundle the curator source with my deployment and therefore makes upgrading a little trickier. Would it be possible to move some of the functionality that is offered by the CLI API into the curator API? i.e. so that someone could use curator from source or from CLI without needing to write code, just supply an action file and configuration file?

**Comment by untergeek** [comment]
> Would it be possible to move some of the functionality that is offered by the CLI API into the curator API? i.e. so that someone could use curator from source or from CLI without needing to write code, just supply an action file and configuration file?

That's an interesting idea.  It _could_ be as simple as renaming the `cli` function to something else, like `process_configuration`:

```
def process_configuration(config, action_file, dry_run=False):
```
I'd re-order the arguments so that `dry_run` is a keyword arg with a default of `False`.

Once this was done, I'd rebuild the `cli` function to point to the `process_configuration` function:

```
@click.command()
@click.option('--config',
    help="Path to configuration file. Default: ~/.curator/curator.yml",
    type=click.Path(exists=True), default=settings.config_file()
)
@click.option('--dry-run', is_flag=True, help='Do not perform any changes.')
@click.argument('action_file', type=click.Path(exists=True), nargs=1)
@click.version_option(version=__version__)
def cli(config, dry_run, action_file):
    process_configuration(config, action_file, dry_run)
```

Your wrapper function would then only have to call `process_configuration` (I'm not settled on the name yet) to get the same effect as you have now.

What do you think?

**Comment by untergeek** [comment]
It would result in a _ton_ of refactoring how the integration tests are called, but it'd be cleaner.

**Comment by dmcd** [comment]
Sound good to me and yes I imagine a bit of work in the documentation too. 
I think that's a clean solution. Its not a high priority for me at the moment as I'm fairly content with my work around for now. 

Thanks for building curator! I'm really happy with how its working in my environment.

**Comment by dmcd** [comment]
How about "run" for the name of the function?
