### ISSUE TITLE
[FEATURE] allow `count` filter to operate on groups

### ISSUE THREAD

**Issue by HonzaKral** [elastic/curator#1044]
add `pattern` parameter to `count` filter that would allow it to operate
within groups: given indices `[logs-1, logs-2, logs-3, metrics-1, metrics-2]`
the filter
```
- filtertype: count
  count: 1
  pattern: '^(.*)-\d$'
  reverse: true
```
will produce `[logs-3, metrics-2]` - a list composed of last index for
every prefix.

The motivation for this is to be able to identify `active` indices in a rollover index group.

**Comment by untergeek** [comment]
So, @HonzaKral, if I understand it correctly, you want to keep the last `count` indices in each matching group, rather than have to specify each prefix at a time?  This is great territory for those who are careful with their regexes, but potentially catastrophic for people who suddenly add new indices that match the pattern, but don't pay attention.

I think it's a worthy feature, but it'll result in multiple iterations, one for each matching group found (but no extra API calls).

**Comment by HonzaKral** [comment]
> keep the last count indices in each matching group, rather than have to specify each prefix at a time

Exactly - if I have `logs-` and `metrics-` I don't want to have 2 different curator configs that contain the same logic (and that I will inevitably forget to update when I add another group). Essentially having the filter act upon groups as defined by prefix via something like `itertools.groupby` (0).

I absolutely agree that it can be potentially disastrous so there are several steps we can take to limit the reach like explicitly white-list prefixes. I do think, however, that a strict warning in the docs and a very safe example (since I assume most people are like me and copy-paste the examples in docs) ought to be enough...

0 - https://docs.python.org/3.5/library/itertools.html#itertools.groupby
