### ISSUE TITLE
[FEATURE] Allow index filtering based on number of shards

### ISSUE THREAD

**Issue by tschroeder-zendesk** [elastic/curator#1071]
Currently there is no way to filter indices on number of shards with the new shrink api this would be particularly useful as you cannot shrink something to 1 shard that already has 1 shard. So, by adding this filter as an exclude that error can be eliminated without having to ignore errors.

**Comment by untergeek** [comment]
This is a good idea.  Thanks for submitting this.

**Comment by untergeek** [comment]
Though, if you've named your shrunk indices with a uniform suffix, e.g. `-shrunk`, then it's easy to filter those.

**Comment by tschroeder-zendesk** [comment]
Yeah I did that for my filters, but in my testing environment I had a few indexes that already had 1 shard so they caused this issue. I can easily work around it, but it seemed like it would be a good feature to have.

**Comment by untergeek** [comment]
> it seemed like it would be a good feature to have.

Agreed.

**Comment by orphaner** [comment]
+1

**Comment by cushind** [comment]
Any update on this? Currently we are running a shrink action on a large number of indices, and we have a few that cannot be shrunk because they are already at 1 shard. This essentially prevents the shrink action from working on any of the other indices that are valid shrink targets, and I do not want to have to manually exclude indices in the filter list.

**Comment by untergeek** [comment]
@cushind Are you not renaming indices by appending a suffix after shrinking?  That is a simple work-around as it allows the suffix to be excluded.

**Comment by cushind** [comment]
@untergeek If my understanding is correct the shrink action will fail entirely if the current index already has the target number of shards. It will not move on to the next index, apply any post-shrink prefix or suffix, or and post allocation settings.

**Comment by cushind** [comment]
Should this filter type be exposed through the curator api or be implicit on every shrink action? In other words, the default filter should exclude any index whose current number of shards is less than or equal to the target shrink number of shards, but would it ever make sense to explicitly set this value.

I'm wondering if someone might want to shrink only those indices with some upper percentile of shards, instead of every index that meets the default criteria. And would a # of shards filter be relevant for any other curator action, like possibly forcemerge which is ofter done in conjunction with shrinking?

**Comment by cushind** [comment]
Ok sounds good. I can get a PR for this in the next couple of days if that would help you out.

**Comment by untergeek** [comment]
Would love a PR.

**Comment by cushind** [comment]
@untergeek Got a PR in. Let me know what you think.
