### ISSUE TITLE
Allow for date math operation in snapshot names

### ISSUE THREAD

**Issue by moogly81** [elastic/curator#1078]
Hi ,
I would like this to work, as it does on the create index action : 

---
actions:
  1:
    action: snapshot
    description: description
       options:
      repository: myrepo
      name: '**<snapshots-{now/d-5d}>**'
...
    filters:
...

Here's my use case .  I store logs in ES. 
I allow  a log to come until 5 days later. (in case of a network disconnected or something like that)
After 5 days, I make a snapshot of that day's indices. 

Great product !
Thanks a lot !

**Comment by chjohnst** [comment]
I would find this useful as well since I roll my indexes daily and taking a snapshot of yesterdays index with a snapshot name that matches that indexes keeps thinks tidy.

**Comment by lkpatel** [comment]
I also need this features. This feature is there in create_index action. In my opinion, this should also extended to other actions also.

**Comment by neilrberry** [comment]
I agree - this feature will be helpful for exactly the same reasons above.

**Comment by untergeek** [comment]
Oh, it'd be very nice to have it exactly the same, but that will be a lot more coding than I'm willing to add right now.  Here's why:  [Date math support in _index_ names](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/date-math-index-names.html) (emphasis mine).

Elasticsearch does the work for this for the `create_index` action.  That's why it works there.  The problem with adding this for snapshot names is that it isn't supported by Elasticsearch, so I'd have to mimic the behavior _exactly,_ or risk upsetting users who expect identical behavior.  I've had my eye on adding this behavior for a while, but it's very difficult to make it happen perfectly, as the libraries and such for Elasticsearch are in Java, and Curator is in Python.

**Comment by untergeek** [comment]
Oh, you're going to love what's coming...

**Comment by untergeek** [comment]
Closed by #1158

**Comment by Alsheh** [comment]
Can this feature be extended (or has been extended) to the repository name as well?

**Comment by untergeek** [comment]
@Alsheh 

Adding it to the Curator code for snapshot-time extrapolation wouldn't be hard, but what are you using to generate new repositories on the fly? Are you asking for this to be put into `es_repo_mgr`?

**Comment by Alsheh** [comment]
@untergeek I am trying to move a daily snapshot of indices to Amazon Glacier with the ability to restore them later as needed. However, moving a snapshot individually from a repository doesn't seem to be possible. So, I am creating a daily repository (hence the need for a dynamic date name) and moving that entire repository to Glacier. Extending the date math operation to the repository name would be great!
