### ISSUE TITLE
Per index requests

### ISSUE THREAD

**Issue by tomsommer** [elastic/curator#1080]
I'm trying to set allocation on a ton of indexes, on a somewhat slow ES-installation.

My problem is that it seems the bulk request to change routing doesn't work, and a 'per-index' URL-request would solve the problem. It would be a nice config option to be able to disable bulk URL-requests.

Currently it fails with:
```
run:184  Failed to complete action: allocation.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=30))
```

And from ES:
```
Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (update-settings) within 30s
```

**Comment by untergeek** [comment]
If increasing the client `timeout` to something larger than 30 doesn't work, then you do, indeed, have a cluster problem.  It is true, that an overburdened cluster can take a lot of time to process metadata changes and propagate them to all nodes in the cluster.  This is, however, indicative of a cluster in need of more resources, rather than a fault in Curator.  Elasticsearch was made to handle bulk responses.  Curator used to do what you are requesting, and it was horribly underperforming. It hammered Elasticsearch with unnecessarily redundant API calls.

My recommendation, if you can't increase cluster resources (more nodes, more memory, faster disks, etc), would be to reduce the response time/overhead by trying smaller batches of indices, limiting the number of indices you're changing allocation on in a single run.

**Comment by tomsommer** [comment]
That's fair enough, but I could solve my performance problem with Curator and individual allocation-queries per index (archiving), so an option to use this method, would be very helpful.

**Comment by untergeek** [comment]
I recommend using a shell-scripted loop, then using `curator_cli`, rather than the full version of Curator that uses a YAML-based action file.

The approach would be to build a list of indices with one iteration that uses a `--filter_list` to select indices, just as you're doing now.  Then on each iteration of the loop, call 
```
curator_cli allocation [OPTIONS] --filter_list \{\"filtertype\":\"pattern\",\"kind\":\"regex\",\"value\":\"\^$INDEXNAME\$\"\}
```
where `$INDEXNAME` is the index from the loop.

It might look something like this:

```
for INDEX in $(curator_cli show_indices --filter_list \{\"filtertype\":\"pattern\",\"kind\":\"regex\",\"value\":\"\^netflow\"\}); do
  curator_cli allocation [OPTIONS] --filter_list \{\"filtertype\":\"pattern\",\"kind\":\"regex\",\"value\":\"\^$INDEX\$\"\}
```

This loop will iterate over all indices that start with `netflow`.  You can add more filters by making them a JSON array—effectively translating what you have in the YAML to a single string.

Obviously, you'd have to replace `[OPTIONS]` with what you want for your allocation, but this will do a single action at a time, like you're asking.

**Comment by untergeek** [comment]
Going to close this since there has been no further response.
