### ISSUE TITLE
New Version for Elasticsearch 6.x ?

### ISSUE THREAD

**Issue by hartfordfive** [elastic/curator#1095]
When will the updated 6.x version be released? Would be nice to be able to start migrating the related code so that I can do a relatively quick upgrade to 6.x on all ELK stack items once it becomes GA.

**Comment by untergeek** [comment]
It's under active development right now.  There's a major refactor being done, and some changes to how things are being handled, mostly due to API changes in 6.  It's not a trivial upgrade, unfortunately.  Many parts won't have to change, but a few will.

I'm also trying to make 6.x less version dependent than 5.x, which is, I think, a necessary improvement.

Long story short, it might not be on time for the 6.0 GA release.

Closing this in favor of #1030 (which predates this issue).
