### ISSUE TITLE
Entire indices getting deleted does not reflect the setting in filtertype age

### ISSUE THREAD

**Issue by bamb00** [elastic/curator#1113]
Hi,

The filter_type unit count is set to '29' and the unit is set to 'days'.  I was expecting the curator client to delete indices that is over 29 days old.  There were a total of 30 indices rotated including the current day and it end up deleting all indices.  And still it continue to delete the current indices even though the unit_count is still set at 29.

The filter type is use in action_file.yml below via Configmap.

What am I doing wrong?

action_file.yml:
---
actions:
  1:
    action: delete_indices
    description: "Clean up ES by deleting old indices"
    options:
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 29
      field:
      stats_result:
      epoch:
      exclude: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-

Pod output:
2017-11-30 21:05:10,487 INFO      Preparing Action ID: 1, "delete_indices"
2017-11-30 21:05:10,511 INFO      Trying Action ID: 1, "delete_indices": Clean up ES by deleting old indices
2017-11-30 21:05:10,523 INFO      Deleting selected indices: [u'logstash-2017.11.30']
2017-11-30 21:05:10,523 INFO      ---deleting index logstash-2017.11.30
2017-11-30 21:05:10,584 INFO      Action ID: 1, "delete_indices" completed.
2017-11-30 21:05:10,584 INFO      Job completed.

Thanks in Advance.

**Comment by bamb00** [comment]
I'm running the provided configmap file and is not working correctly according to the settings in the action_file.

**Comment by bamb00** [comment]
@untergeek Not sure why you close this issue #1113.  I cannot go on the elasticsearch community and ask how the configmap action_file.yml settings is correct or not.  It does not hurt just to review the file if the format is correct.

**Comment by untergeek** [comment]
Yes, you can ask questions there.  I answer there personally.

**Comment by untergeek** [comment]
I'm sorry if I sound terse, or curt.  The Curator GitHub issues area is getting more and more crowded with usage questions, instead of bug reports and feature requests.  The issues section is not the correct place for usage questions, unless they are actually a bug.  While you may feel that you have a bug on your hands, it's much more useful for the eyes of the community (and myself) to have a centralized location where others with experience can respond, not just me.

I've even gone so far as to add issue and pull request templates, to help direct usage questions to the correct location.  I'm sure there's a good explanation for what you're experiencing, but an issue here on GitHub will wind up closed, and ignored, where the discussion threads remain open and searchable by many users.

**Comment by untergeek** [comment]
I prefer you open it there, because now that I edited your initial comment to encapsulate the plain text bits in triple back ticks, I can see exactly what happened.  It's not a bug.  It's a usage issue.

**Comment by bamb00** [comment]
@untergeek  Thanks for pointing me to the elasticsearch discussion page.  I was able to see what I'm doing wrong.
