### ISSUE TITLE
[FEATURE] Add per index_space based filtertype

### ISSUE THREAD

**Issue by jantoniogarcia** [elastic/curator#1151]
I' set up a hot-warm elastic cluster. The Indices in the cluster have different sizes (from 50mb to 200GB) with different shard count (3 up to 10).

Once i moved the index to the 'warm' nodes, it will be useful if i can shrink it to a number of shards based on it's size (usually related to the node heap memory). 
For example, we can shrink a <4GB index with 3 shards to 1 shard. Or perhaps indexing between 4GB and 8GB to 2 shards and so on. It has less impact moving  4GB shard size rather than 200GB shard size in case of a shard reallocation or node failure. 

Instead of changing the 'shrink' action to permit a shard number based on index size, maybe it will be more useful to just implement an index_space filtertype. This way we can apply different actions (shrink, reallocate, ...) based on the index size.

Thanks in advance

**Comment by untergeek** [comment]
While long requested, the Elasticsearch team has pretty much _always_ recommended that people _not_ use index size as a determining characteristic.  In fact, while it's absolutely possible to have a 200G shard size, we typically recommend that users not let shard sizes grow past 50G, and even 20G-30G as a best-practices maximum.  These recommendations are primarily because we know too well how long it takes for data to migrate between nodes.

I will contemplate adding this feature, but please know if I don't it's mostly because I worry that if Curator supports it, it gives the appearance that Elastic and the Elasticsearch developers put the stamp of approval on cluster practices it doesn't actually recommend.

**Comment by jantoniogarcia** [comment]
I guess i am missing something, i know i have to improve my Elastic knowledge.

But, taking in consideration the shard size recomendations, it is hard to take any action to prevent that growth if you can not use the index or shard size as a determining characteristic.

Another example is the Rollover API.  It has a _max_size_ condition filter (for 6.X versions). I guess curator does not has it for 5.X compatibility.

Maybe i need a hint on how i have to work with my data and curator to prevent that shard growth, instead of adding some custom scripts in between curators jobs.

Thank you

**Comment by untergeek** [comment]
There is a request for `max_size` to be added to Curator, but it's a bit of a pain as that has to have tests to only work in 6.1+ or 6.2+ as it isn't in any other versions.  While it's not impossible for it to be used in other cases, it was specifically targeted at users who use a single shard index and want to rollover when it hits a designated shard size.  Also, Rollover indices almost certainly will not be the product of specific shard routing type indexing, where a given shard will be bigger than another.  It is because of these changes that `max_size` was even considered.

**Comment by untergeek** [comment]
`max_size` was recently merged.  If you are using 6.1 or higher, then that will be available to you.
