### ISSUE TITLE
Curator optimize operation request_timeout gets override by default value of 21600

### ISSUE THREAD

**Issue by sravankumar777** [elastic/curator#1168]
Logstash & Marvel indices can be optimized with curator optimize operation.
By default value of 21600 is being considered for curator optimize operation for logstash & marvel indices. 
Configuration value(5000) from the user is being override with the default value. 

### Expected Behavior
It is required to consider the configuration value for the timeout operation.
Like 5000 timeout value instead of 21600(default value).

### Actual Behavior
Configured value is always override by the default value.

### Steps to Reproduce the Problem
1. Perform curator optimize operation on the logstash & marvel indices in an elastic search cluster with request_timeout attribute value as 5000 secs. 
2. Check for the curator log while the optimize operation is being executed.  

### Specifications

  - Version: Curator version 3.4.0

**Comment by untergeek** [comment]
Curator 3.4 only [overrides](https://github.com/elastic/curator/blob/v3.4.0/curator/cli/index_selection.py#L69) the [default value of 30 seconds](https://github.com/elastic/curator/blob/v3.4.0/curator/cli/cli.py#L25) if [no default value is provided](https://github.com/elastic/curator/blob/v3.4.0/curator/cli/optimize.py#L13-L19)

The code that overrides that value is [here](https://github.com/elastic/curator/blob/v3.4.0/curator/cli/utils.py#L146-L150).

The [`--request-timeout` flag value](https://github.com/elastic/curator/blob/v3.4.0/curator/cli/optimize.py#L13-L15) is different, and doesn't work correctly or have an effect beyond the regular client `--timeout` value, which is why this setting is omitted in future versions of Curator.

You should know that Curator 3.5.1 is the last one in the Curator 3.x series, and was release 2016-03-21—nearly 2 years ago.  The version you're using, 3.4.0, was released 2015-10-28, well over 2 years ago.  Neither version is supported any longer, as the versions of Elasticsearch they support are no longer supported either.  If you are compelled to use an older version of Curator, you should at least use version 3.5.1, with the latest settings.  If you're stuck with 3.4.0, you probably got it from an alternate repository, as that's the latest version I've seen bundled in some of those repositories.  You can use the [official repositories](https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/installation.html) for 3.5 to download a newer version of the 3.x series.  By way of comparison, Curator 4 supports Elasticsearch 2.x and 5.x installs.  Curator 5 supports Elasticsearch 5.x and 6.x installs.

Since the version you're requesting a change for is very much no longer supported, this issue will be closed.

**Comment by sravankumar777** [comment]
Thanks for detailed information @untergeek.
With other dependencies on our system, we are stuck with curator version of 3.4.0.
However, we plan to upgrade with the latest version.
