### ISSUE TITLE
Bug with Rollover when using new_index

### ISSUE THREAD

**Issue by danielkasen** [elastic/curator#1220]
When I try to use the rollover index it will work the first time but then later attempts try to do a rollover even though the conditions set are false. I noticed this only happens when I use the new_index setting on curator 5.5.2 

```actions:
  1:
    action: rollover
    description: >-
      Rollover the test index
    options:
      name: test
      wait_for_active_shards: all
      conditions:
        max_size: 700gb
      new_index: "<test-{now/H{YYYY.MM.dd.HH}}-1>"

Log output:

{"@timestamp": "2018-05-19T21:24:24.411Z", "function": "run", "linenum": 165, "loglevel": "INFO", "message": "Trying Action ID: 1, \"rollover\": Rollover the test index", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.412Z", "function": "process_action", "linenum": 44, "loglevel": "DEBUG", "message": "Configuration dictionary: {'action': 'rollover', 'description': 'Rollover the test index', 'options': {'name': 'test', 'conditions': {'max_size': '700gb'}, 'new_index': '<test-{now/H{YYYY.MM.dd.HH}}-1>', 'wait_for_active_shards': 'all', 'extra_settings': {}}}", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.412Z", "function": "process_action", "linenum": 45, "loglevel": "DEBUG", "message": "kwargs: {'master_timeout': 30, 'dry_run': False}", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.412Z", "function": "process_action", "linenum": 50, "loglevel": "DEBUG", "message": "opts: {'name': 'test', 'conditions': {'max_size': '700gb'}, 'new_index': '<test-{now/H{YYYY.MM.dd.HH}}-1>', 'wait_for_active_shards': 'all', 'extra_settings': {}}", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.412Z", "function": "process_action", "linenum": 62, "loglevel": "DEBUG", "message": "Action kwargs: {'conditions': {'max_size': '700gb'}, 'new_index': '<test-{now/H{YYYY.MM.dd.HH}}-1>', 'extra_settings': {}, 'name': 'test', 'wait_for_active_shards': 'all'}", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.412Z", "function": "__init__", "linenum": 860, "loglevel": "DEBUG", "message": "\"conditions\" is {'max_size': '700gb'}", "name": "curator.actions.rollover"}
{"@timestamp": "2018-05-19T21:24:24.414Z", "function": "parse_date_pattern", "linenum": 1338, "loglevel": "INFO", "message": "\"<test-{now/H{YYYY.MM.dd.HH}}-1>\" is using Elasticsearch date math.", "name": "curator.utils"}
{"@timestamp": "2018-05-19T21:24:24.415Z", "function": "parse_date_pattern", "linenum": 1349, "loglevel": "DEBUG", "message": "Fully rendered name: <test-{now/H{YYYY.MM.dd.HH}}-1>", "name": "curator.utils"}
{"@timestamp": "2018-05-19T21:24:24.418Z", "function": "process_action", "linenum": 99, "loglevel": "DEBUG", "message": "Doing the action here.", "name": "curator.cli"}
{"@timestamp": "2018-05-19T21:24:24.418Z", "function": "do_action", "linenum": 942, "loglevel": "INFO", "message": "Performing index rollover", "name": "curator.actions.rollover"}
{"@timestamp": "2018-05-19T21:24:24.420Z", "function": "run", "linenum": 184, "loglevel": "ERROR", "message": "Failed to complete action: rollover.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: TransportError(400, u'resource_already_exists_exception', u'index [test-2018.05.19.21-1/guf3-e04SZKgLoN0NVy3mg] already exists')", "name": "curator.cli"}

**Comment by untergeek** [comment]
It's not a bug.  It's Elasticsearch telling you that you can't name the index the same as one already in existence.  Elasticsearch gives you the exact same error if you do this manually.  I'll show you what happens using console, as follows.

I'll create this one, like what you have: 
```
PUT %3Ctest-%7Bnow%2FH%7BYYYY.MM.dd.HH%7D%7D-1%3E
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  },
  "aliases": {
    "test": {}
  }
}
```
_(You have to use URL-encoding for those characters in Console. It's exactly the same sequence you provided:_ `<test-{now/H{YYYY.MM.dd.HH}}-1>`_)_

Here's the result:
```
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "test-2018.05.19.21-1"
}
```
Now, if I send a rollover request, with that same name _in the same hour:_
```
POST /test/_rollover/%3Ctest-%7Bnow%2FH%7BYYYY.MM.dd.HH%7D%7D-1%3E
{
  "conditions": {
    "max_age":   "1s"
  }
}
```
This is the result (which is what you're getting in Curator):
```
{
  "error": {
    "root_cause": [
      {
        "type": "resource_already_exists_exception",
        "reason": "index [test-2018.05.19.21-1/qdStmzQsRqCwJOj1VSZgJQ] already exists",
        "index_uuid": "qdStmzQsRqCwJOj1VSZgJQ",
        "index": "test-2018.05.19.21-1"
      }
    ],
    "type": "resource_already_exists_exception",
    "reason": "index [test-2018.05.19.21-1/qdStmzQsRqCwJOj1VSZgJQ] already exists",
    "index_uuid": "qdStmzQsRqCwJOj1VSZgJQ",
    "index": "test-2018.05.19.21-1"
  },
  "status": 400
}
```

You see the same `400` error with the accompanying `resource_already_exists_exception` in your Curator log.  Because you're doing a named-by-hour rollover, and since the hour hasn't rolled over, ending with `-1` means a collision, as the number cannot increase.  

## Proposed Solution
I think what you want is to do is describe the name pattern just once.

If I change the index creation pattern to be per minute (I'm not going to wait an hour to demonstrate this):

```
%3Ctest-%7Bnow%2Fm%7BYYYY.MM.dd.HH.mm%7D%7D-1%3E
(which is <test-{now/m{YYYY.MM.dd.HH.mm}}-1>)
```
I get an index named: `test-2018.05.19.22.02-1`

When I rollover _within the same minute_ and do **not specify a new index name**, I will see this output:
```
{
  "old_index": "test-2018.05.19.22.02-1",
  "new_index": "test-2018.05.19.22.02-000002",
  "rolled_over": true,
  "dry_run": false,
  "acknowledged": true,
  "shards_acknowledged": true,
  "conditions": {
    "[max_age: 1s]": true
  }
}
```
Please note that you cannot prevent Elasticsearch from the zero-padding of the trailing number with this approach.  [This is documented](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-rollover-index.html#_naming_the_new_index):
> If the name of the existing index ends with `-` and a number — e.g. `logs-000001` — then the name of the new index will follow the same pattern, incrementing the number (`logs-000002`). The number is zero-padded with a length of 6, regardless of the old index name.

Subsequently, if I rollover in a new minute, and **do not specify a new index name**, I will see this output:
```
{
  "old_index": "test-2018.05.19.22.02-000002",
  "new_index": "test-2018.05.19.22.04-000003",
  "rolled_over": true,
  "dry_run": false,
  "acknowledged": true,
  "shards_acknowledged": true,
  "conditions": {
    "[max_age: 1s]": true
  }
}
```
Elasticsearch automatically preserves the naming pattern (`test-2018.05.19.22.02` moves to `test-2018.05.19.22.04`) and just appends digits to the end.  No more naming magic required from you, which is needed if you will have more than 1 index per date period you have in your index date-math name.

In my mind, it's so much simpler to just have numbered rollovers, e.g. `test-000001` and let Curator do the date math with the `period` and/or `age` filters using the [`field_stats`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html#_literal_field_stats_literal_based_ages) calculated ages.  Then it just doesn't matter when it rolls over.  Even at 2 rollovers per hour, my rough calculation would be 5.7 years worth of digits in a 1 to 99999 count.

**Comment by untergeek** [comment]
As this issue is not actually a Curator problem, I'm marking it closed.  Please feel free to comment here, if you have further questions.

**Comment by danielkasen** [comment]
Ok, I guess I was under the impression that the conditions check was done before the check to see if the action could be performed. Thank you.

**Comment by upgle** [comment]
Hi @untergeek 
I've tried your suggestion in ES 7.10,  elasticsearch-curator:5.8.4, but it doesn't seem to work.


```
    options:
      name: prefix
      new_index: "<prefix-{now/m{YYYY.MM.dd.HH.mm}}-1>"
      conditions:
        max_age: 1s
```

- <prefix-{now/m{YYYY.MM.dd.HH.mm}}-000001>
    - (expected) 2021.12.23.05.31-000001 -> 2021.12.23.05.33-000002
    - (actual) 2021.12.23.05.31-000001 -> 2021.12.23.05.33-000001
```
2021-12-23 05:33:01,782 INFO      "<prefix-{now/m{YYYY.MM.dd.HH.mm}}-000001>" is probably using Elasticsearch date math.
2021-12-23 05:33:01,789 INFO      Performing index rollover
2021-12-23 05:33:01,845 INFO      Old index prefix-2021.12.23.05.31-000001 rolled over to new index prefix-2021.12.23.05.33-000001
```

- <prefix-{now/m{YYYY.MM.dd.HH.mm}}-1>
    - (expected) 2021.12.23.05.34-1 -> 2021.12.23.05.35-000002
    - (actual) 2021.12.23.05.34-1 -> 2021.12.23.05.35-1
```
2021-12-23 05:35:44,501 INFO      "<prefix-{now/m{YYYY.MM.dd.HH.mm}}-1>" is probably using Elasticsearch date math.
2021-12-23 05:35:44,508 INFO      Performing index rollover
2021-12-23 05:35:44,567 INFO      Old index prefix-2021.12.23.05.34-1 rolled over to new index prefix-2021.12.23.05.35-1
```

### REST API (works well)


```
POST myindex/_rollover
{
  "conditions": {
    "max_age":   "1s"
  }
}

{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "old_index" : "myindex-2021.12.23.05.35-1",
  "new_index" : "myindex-2021.12.23.05.40-000002",
  "rolled_over" : true,
  "dry_run" : false,
  "conditions" : {
    "[max_age: 1s]" : true
  }
}
```
