### ISSUE TITLE
Curator started reporting error in delete_indices ‘An HTTP line is larger than 4096 bytes.’ 

### ISSUE THREAD

**Issue by MohammadRamadan** [elastic/curator#1224]
Hello Friends,
I have ELK stack with curator installed to delete logs older than 365 days.
a script created is used to make this process under crontab job that used to delete these older than 365 days logs.
everything was going well for days and suddenly when checking the job logs I found it report and error as follow :
2018-05-21 13:02:19,057 INFO Preparing Action ID: 1, "delete_indices"
2018-05-21 13:02:19,067 INFO Trying Action ID: 1, "delete_indices": Delete indices older than 365 days (based on index name), for custom- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2018-05-21 13:02:19,304 ERROR Failed to complete action: delete_indices. <class 'elasticsearch.exceptions.RequestError'>: TransportError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')
versions data as follow:
di@ELK-5:$ curl -XGET 'localhost:9200'
{
"name" : "QInEGiG",
"cluster_name" : "elasticsearch",
"cluster_uuid" : "SEqBRvyiSjCBPJLpMBVgrg",
"version" : {
"number" : "5.6.5",
"build_hash" : "6a37571",
"build_date" : "2017-12-04T07:50:10.466Z",
"build_snapshot" : false,
"lucene_version" : "6.6.1"
},
"tagline" : "You Know, for Search"
}
di@ELK-5:$
curator, version 5.4.1
Any help guys, am network engineer and not a developer :(
TIA

**Comment by sadiesh** [comment]
"http.max_initial_line_length" has to added in ES yaml file

**Comment by MohammadRamadan** [comment]
Thank you, adding this parameter to the yml file solved it.

**Comment by untergeek** [comment]
I'd like to know more about how this happened.  Curator shouldn't experience this as there is [code that tries to prevent chunks bigger than roughly 3K from being sent](https://github.com/elastic/curator/blob/v5.5.3/curator/utils.py#L606-L627), because of this 4K limit.  This code has been in place for a lot longer than Curator version 5.4.1 (the version you are using).

How large are your index names?  Is there more log data than what you've provided?

**Comment by MohammadRamadan** [comment]
Hi, as told before am not a developer so I would reply to you with any information you would but explain plainly and how to answer you ques if necessary.
Thank you

**Comment by untergeek** [comment]
Let's start with these questions:

How large are your index names? Can you give me a sample of what they look like?

Is there more log data than what you've provided?  You only included the error. Was there more?

What is the full text of your action YAML file? I'd like to see how your indices were being selected and filtered.

**Comment by breml** [comment]
I observed this log line during a snapshot restore operation. log output of curator:

```
2019-02-13 07:17:38,507 ERROR                curator.cli                    run:184  Failed to complete action: restore.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: Unable to obtain recovery information for specified indices. Error: TransportError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')
```

The restore operation restores ~280 indices, which is a full restore of a repository.

After this line curator exited, the restore operation in Elasticsearch continued).

```
# curator --version
curator, version 5.5.1
```

@untergeek what else do you need?

**Comment by untergeek** [comment]
@breml This would be a problem. I did not anticipate anyone restoring such a large number of indices at once, I guess. 

At issue is that the verification step is trying to ensure all indices have been restored, but if that index list is too long, it will not get a good response. I may instead have to check for all indices out of a `_cat/indices` call, and verify them that way, rather than pass each index in a CSV list. 

@breml, this should be a separate issue, as yours is specific to restore. Can you open a new issue, please?

**Comment by breml** [comment]
@untergeek I just filed #1360 for the issue I had during restore.
