### ISSUE TITLE
[FEATURE] Rollover Mapping

### ISSUE THREAD

**Issue by chrislujan** [elastic/curator#1234]
The ES API allows for mapping data in the [rollover call](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-rollover-index.html), the curator [create_index](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/create_index.html) action allows for mapping data as well. Is there any reason why the rollover action doesn't allow for mapping?

**Comment by untergeek** [comment]
Mostly from a cleanliness standpoint.  It's a scripted rollover, something that will happen (or so we'd expect) _repeatedly_ at intervals.  Why would you convert a mapping into YAML and embed that into a curator action file when you could just use an index template?  I understand why you might want to change a mapping as a one-off rollover, but that's not where Curator is likely to be used.  You really should be putting mappings into an index template instead of in here.

Could I allow mappings? Sure.  If I do, I will not document the feature, because I don't want to have to support troubleshooting someone's JSON->YAML mapping and explain to them why it didn't work.  It's just not a good thing to be doing with Curator.

**Comment by untergeek** [comment]
The same is mostly true for the `create_index` action, but it's not commonly used.

**Comment by chrislujan** [comment]
I might be misunderstanding how index templates work, but where I noticed a need (want) is when a rollover occurs, the index is created but until a document is indexed, the index doesn't have it's mapping applied from logstash's output. When that empty index is queried, it results in `org.elasticsearch.transport.RemoteTransportException`. Nothing to be worried about, but can result in larger than normal logs, albeit debug loglines. My feature request was more curiosity than anything I guess :) I can understand not wanting to support a feature that results in more headache for you and adds very little function to curator. Thanks for the reply @untergeek

**Comment by untergeek** [comment]
If rollover is not instantaneous, your cluster might be under a bit of strain.  There are, of course, a few moments—usually milliseconds, but sometimes seconds in a busy cluster—when a new index is provisioned in the cluster, and the shards are initialized. While that is happening, and the alias is pointing to the as-yet not-completely provisioned index/shards, Logstash will, of course, not be able to push documents yet.

> when a rollover occurs, the index is created but until a document is indexed, the index doesn't have it's mapping applied from logstash's output.

This is a misunderstanding of how Elasticsearch and Logstash work.

With index templates, the index is created with the required mapping.  There is no delay where documents are indexed improperly because a mapping template has not been applied yet.  _**To be clear:** Logstash does not apply a mapping to indexes._ Ever.  _Logstash does not_ create _an index, ever._ Logstash is a streaming operator.  It sends bulk operations to Elasticsearch.  These operations are essentially "Index event A into index named blah_blah".  If the target index does not exist when one of these bulk requests goes in, Elasticsearch creates the index, not Logstash.  If no mapping is applied to the index, Elasticsearch will guess the mapping (dynamic mapping is on by default).    Logstash _does_ upload a default index template which only applies to indices named `logstash-*`, but this is a very generic mapping.

**Comment by chrislujan** [comment]
thanks @untergeek for the explanation, I can work on a solution from here 👍
