### ISSUE TITLE
Failed to complete action: forcemerge.  <class 'curator.exceptions.NoIndices'>: index_list object is empty

### ISSUE THREAD

**Issue by krishnabigdata** [elastic/curator#1245]
Here is my command to force merge the index by hourly.

`curator_cli --host $elasticsearch_host--timeout 21600 forcemerge --ignore_empty_list --delay 10 --max_num_segments 1 --filter_list '[{"filtertype":"age","source":"name","timestring":"%Y.%m.%d.%H","direction":"older","unit":"hours","unit_count":1}]'`

even though I use **_--ignore_empty_list_** option still I receive the below error if there is no index exist for the hour.

_**CRITICAL  Failed to complete action: forcemerge.  <class 'curator.exceptions.NoIndices'>: index_list object is empty**_

**Versions:**
Curator: **5.5.4**
Elasticsearch: **6.2.4**

Please let me know if you need any more details

**Comment by untergeek** [comment]
The `--ignore_empty_list` option for `curator_cli` doesn't prevent the error message.  It hasn't been fully implemented yet (in `curator_cli`), because its whole reason for being was to allow Curator to proceed to the next action if it was only an empty list condition that caused the error.  

With `curator_cli`, there is no next action, as they are singletons.  You are free to script another action after this without regard to the output of an error.

When I eventually implement this fully, it will still not necessarily prevent the error message. It will simply guarantee that it exits with a zero exit code.

**Comment by untergeek** [comment]
Closing as there is really nothing to be done here.
