### ISSUE TITLE
Curator 5.5.4 not working for AWS Elasticsearch Service 5.3 and 5.5

### ISSUE THREAD

**Issue by jpdoria** [elastic/curator#1246]
`show_indices` doesn't work properly even though I was able to list using `_cat/indices` API.

### Expected Behavior
`show_indices` should display the list of indices from AWS Elasticsearch Service.

### Actual Behavior
No output returned. Exit code is 0. Nothing happened.

### Steps to Reproduce the Problem
  1. Install `curator` using the steps from this [documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/yum-repository.html)
  1. Run `curator_cli --host <AWS_ES_DOMAIN> --port 80 show_indices --loglevel INFO`
  1. Run `curator_cli --host <AWS_ES_DOMAIN> --port 443 show_indices --loglevel INFO`

### Specifications

  - AWS Elasticsearch Service 5.3 and 5.5
  - Curator 5.5.4

**Comment by untergeek** [comment]
I'm thinking that you will need to establish AWS credentials in order to use `curator` or `curator_cli` with AWS ES.  Please see [the documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/configfile.html) for more details around these options, specifically [`aws_sign_request`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.5/configfile.html#aws_sign_request).

**Comment by heroInCommunity** [comment]
Does curator return any output on `curator --help`?
Probably it is related to https://github.com/elastic/curator/issues/1243.

**Comment by untergeek** [comment]
I have no way of testing this. As such, it sits with the tags it has.
