### ISSUE TITLE
Support wait_for_completion on forcemerge action?

### ISSUE THREAD

**Issue by rolodato** [elastic/curator#1258]
I'm running curator on AWS Lambda and it works great. I'd like to run `forcemerge` periodically but this operation can take a really long time to finish on large indices. Setting an absurdly high value won't work because AWS-managed Elasticsearch has a hard timeout on how long requests can run, and even if this were possible, Lambda hard-limits requests to 5 minute durations.

Would it make sense to support `wait_for_completion` on `forcemerge` to improve this situation? Thanks!

**Comment by untergeek** [comment]
Unfortunately, this cannot be easily coded around in any way I have been able to imagine.  The closest I have been able to come has been with the addition of the _tasks API in the most recent releases of Elasticsearch, but it amounts to a gamble and a guess.

The problem is that when you initiate a forceMerge in Elasticsearch, the base Lucene command offers no way to track the results, other than to count the number of segments per shard, which has proven an unreliable way to track status, especially if you accidentally have more data come in.  The only reliable way Elasticsearch allows you to tell if a forceMerge is done is to keep the client connection open until it has returned control to the client.  Should that client connection close while you are waiting—like with your Lambda—there is essentially no way to reconnect to that process without it being that guess and a gamble.  ForceMerges don’t even allow API-level blocking responses.  If one has been initiated and is in progress, you can still initiate another, but it will be opaquely blocked and put on hold until the current one has completed—and Elasticsearch won’t tell you that this is the case.  

The forceMerge API is very ripe for changes that correct these issues, but I don’t know if/when they will ever happen.  As stated, you _can_ see that segments are being forceMerged in the _tasks API now, but there’s no way to track the index they came from, which client process initiated them, or anything else that the _tasks API normally allows you to do.  I have been very hopeful that the _tasks API would allow me to do overcome these shortcomings, but in its current state, it’s no more than a gamble that even using the _tasks API would work as desired, since it would require (at the very least):

1. Dumping all tasks from all nodes
1. Combing through them to find forceMerges that may or may not have been initiated by me
1. Keep doing 1 and 2 until there are no more forceMerges 

The huge problem is that if I query the _tasks API and there has been a slight pause in between new tasks, such that I see no forceMerges, but a few (or several) seconds later, the next shard in the index starts a forceMerge (this is a very real possibility, looking at the monitoring data. The replica shards are sometimes the last to do the forceMerge, and can have delays in between), Curator may mistakenly think that the forceMerge is done when it is not.  It would be no problem, if a real parent task were created, complete with a task ID. But a task ID is not generated by Elasticsearch for a forceMerge, which makes this a guess and a gamble.

Since you’re already using a Lambda, and you will be using the API for this, rather than Curator directly, your best bet will be to code around this as best you can by combining the tasks API with the expected `max_num_segments` and hope that it’s all done.  It is a lot of extra coding I wish you didn’t have to do, but it’s the only hope anyone currently has to overcome the API shortcomings I outlined, and those are still a guess and a gamble.  There are just no concrete solutions yet.

**Comment by rolodato** [comment]
Hey @untergeek, thanks for the super detailed response.

I think my original question wasn't clear but I was looking for the opposite behaviour - I'd like Curator to "fire and forget" when calling `_forcemerge`, assuming that the merge request was valid and accepted (not sure if Elasticsearch provides a way to know this). In this case, I wouldn't be able to wait for a response since AWS Elasticsearch would return a 504 long before the merging is complete, and likely the Lambda function would time out as well. Hope that makes sense, thanks again!

**Comment by untergeek** [comment]
No.  [There is no such thing](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-forcemerge.html).  As I tried to explain:

> This call will block until the merge is complete. If the http connection is lost, the request will continue in the background, and any new requests will block until the previous force merge is complete.

**Comment by untergeek** [comment]
Your best bet would be to spin up a second, parallel client with a relatively short timeout (before the default) and use that to execute the forceMerge, knowing that it will fail.  If you only have one index to forceMerge, this is your "best effort."

It gets significantly more complicated, though, if you have several indices per day to forceMerge.  This is why I outlined the scenario above, and what you'd have to do to make sure it detected when an index had completed the forceMerge, so it could schedule the next.

I emphatically do not recommend trying to forceMerge more than one index at a time.  Yes, the API allows you to pass multiple indices to a forceMerge command.  The I/O load on the cluster could easily become crippling to ongoing indexing, merging, and querying operations.

**Comment by rolodato** [comment]
I see, thanks very much for the suggestions! Do you know if there's an issue that I or others can track for forcemerge improvements in Elasticsearch?

**Comment by untergeek** [comment]
> Do you know if there's an issue that I or others can track for forcemerge improvements in Elasticsearch?

I am not aware.  You should visit https://github.com/elastic/elasticsearch to check their issues for an existing one.  If one isn't there, you could add one.
