### ISSUE TITLE
Curator delete crashes if encountering an old timestamp

### ISSUE THREAD

**Issue by rsteneteg** [elastic/curator#1295]
### Expected Behavior
Curator delete should not crash when trying to clean up indices

### Actual Behavior
Curator starts up and exits before any indices has been cleaned up with this error `Unusually formatted epoch timestamp. Should be 10, 13, or more digits`

We are running a curator job that runs this filter to look for old indices
```
- filtertype: age
      source: field_stats
      direction: older
      unit: days
      unit_count: 14
      field: '@timestamp'
      stats_result: max_value
```
However some host was started with an incorrect timestamp (year 1988), creating documents with a 12 digit timestamp, which was then set as the min_value for the index field_stats.

### Specifications

  - Version: ES 5.6.6, Curator 5.5.4

## Context (Environment)
We do index rollovers and deletions of indices older than 14 days. When a host sent in some docs with a very old timestamp from year 1988, Curator would crash complaining about a 12 digit timestamp, causing no indices to be deleted. With no old indices deleted we started growing in disk usage. Once the bad host was fixed, we tried to exclude the two indices we got with 12 digit timestamps but Curator runs the fix_epoch function on all indices at startup so exclude did not work.

## Detailed Description
I don't have the context for why 12 digit timestamps are not allowed in the first place, but I have created a code fix to allow it.

**Comment by untergeek** [comment]
Sorry you've had a bad experience with Curator.  The reason for the timestamp length being 10 or 13 is because sometimes epoch timestamps comes with milliseconds, sometimes without.  It's super hard for Curator to know which is which.  The date math would be off significantly if Curator expected the wrong one and ended up being off by 3 orders of magnitude.

You've hit an edge case I did not anticipate, nor do I have any quick solutions.  I will review your pull request and consider it.
