### ISSUE TITLE
Unable to complete action "close".  No actionable items in list: <class 'curator.exceptions.NoIndices'>

### ISSUE THREAD

**Issue by GlamorCodius** [elastic/curator#1403]
I'm relatively new to elasticsearch and curator (I'm still learning). I was following the following elastic search documentation: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html

I just want to close all the indices that are older than 1 day. However, for some reason it's not working. I will share my config.yml as well as my action file and the output of the DEBUG. As a final note, I didn't change much from what the elastic.co documentation specified I should do.

Config.yml:

`client:`
  `hosts:`
    `- 127.0.0.1`
  `port: 9200`
  `url_prefix:`
  `use_ssl: False`
  `certificate:`
  `client_cert:`
  `client_key:`
  `ssl_no_validate: False`
  `http_auth:`
  `timeout: 30`
  `master_only: False`

`logging:`
  `loglevel: DEBUG #INFO`
  `logfile:`
  `logformat: default`
  `blacklist: ['elasticsearch', 'urllib3']`

closeactionfile.yml:

`actions:`
  `1:`
    `action: close`
    `description: >-`
     `Close indices older than 1 day (based on index name), for packetbeat-`
     `prefixed indices.`
    `options:`
      `delete_aliases: False`
      `disable_action: False`
    `filters:`
    `- filtertype: pattern`
      `kind: prefix`
      `value: packetbeat-`
    `- filtertype: age`
      `source: name`
      `direction: older`
      `timestring: '%Y.%m.%d'`
      `unit: days`
      `unit_count: 1`

I will be putting in a file the output of the DEBUG when I run the following command on my terminal `curator --config /Users/johnsmith/Desktop/ELK/config.yml /Users/johnsmith/Desktop/ELK/closeactionfile.yml`
[DEBUG output.txt](https://github.com/elastic/curator/files/3181732/DEBUG.output.txt)

If someone can tell me what I did wrong it would be very appreciated thank you!

**Comment by untergeek** [comment]
Happy to help.

To begin, a few tips for future requests:

Please encapsulate all pasted configs and data between triple back ticks:

    ```
    PASTE HERE
    ```

Without doing this, it's impossible to tell whether your YAML is properly indented.

Next, for usage and configuration questions, it is advisable to search and/or post to the [Elastic Discussion forums](https://discuss.elastic.co/c/elasticsearch) first. If it turns out what you have encountered is a bug, then filing a GitHub issue is appropriate.

With those two items mentioned, I see this in the shared output:

```
All indices: ['.kibana_task_manager', '.kibana_1', 'packetbeat-7.0.0-2019.05.10-000001']
```
So, there are only those 3 indices during the initial run. Then I found:
```
2019-05-15 11:43:37,196 DEBUG          curator.indexlist             filter_ilm:1176 Filtering indices with index.lifecycle.name
2019-05-15 11:43:37,198 DEBUG          curator.indexlist       __not_actionable:39   Index packetbeat-7.0.0-2019.05.10-000001 is not actionable, removing from list.
```
It appears you are using version 7 of Packetbeat, which applies ILM policies to its indices. With a Basic license, you could achieve this kind of index retention automatically, without the need for Curator.

If you still want to use Curator, you will need to use the [as-yet undocumented](#1402) `option`: 

```
allow_ilm_indices: true
```

Without this set, Curator will automatically exclude indices which are associated with an ILM policy, whether you are using it or not.

**Comment by untergeek** [comment]
ILM now fully documented in #1404

**Comment by prateekshekhar-31** [comment]
You need to add this in the options section in action.yml
`allow_ilm_indices: true`
