### ISSUE TITLE
delete action；why?

### ISSUE THREAD

**Issue by k-kyle** [elastic/curator#1423]
404 always appears when deleting, and needs to be executed multiple times.
-------------------------------------------------------------------------------------
ERROR     Failed to complete action: delete_indices.  <class 'curator.exceptions.FailedExecution'>: Exception encountered.  Rerun with loglevel DEBUG and/or check Elasticsearch logs for more information. Exception: NotFoundError(404, u'index_not_found_exception', u'no such index')

**Comment by untergeek** [comment]
This is mentioned many times in the discussion forums at https://discuss.elastic.co

For some background, Curator is Python based, and uses the `elasticsearch` Python module, which uses `urllib3` to connect to Elasticsearch. 

There are two scenarios where the 404 thing happens:

1. If a `delete_indices` action returns "ok", but a subsequent sanity check of the cluster state shows the indices are still there, Curator itself will re-try the delete. If the delete completes in the few milliseconds before the retry starts, Elasticsearch will return a 404, because the index is truly not found—even though it _was_ found a few milliseconds ago.
2. If a timeout occurs while waiting for a REST request to complete, `urllib3` will automatically retry the previous request. As with the above scenario, this can result in some indices already being deleted, resulting in a 404.

In both of these scenarios, the common factor is a cluster which is processing the cluster state too slowly, resulting in either Curator or `urllib3` attempting to retry deletes. **Chances are good your cluster is overloaded in some way.** This 404 is an inconvenience, but does not otherwise affect the cluster adversely. If you were hoping to have Curator proceed to another action after `delete_indices`, then this poses a problem. While I do have some plans in place to address these retries, they will not be available in the near future. Your best remedy in the near term is to address the slowness in updating the cluster state that results in the retry or timeout scenario.

**Comment by k-kyle** [comment]
I understand, thank you for your reply.
