### ISSUE TITLE
Curator not removing the indices "curator.exceptions.NoIndices"

### ISSUE THREAD

**Issue by vasanthchellappa** [elastic/curator#1489]
When i run curator to delete the indices, throwing me no indices error. I assume i did found the error, but i don't how to resolve the same. Kindly help me on this, here is the config.

actions:
1:
action: delete_indices
description: >-
Delete indices older than 3 days (based on index name), for logstash-
prefixed indices. Ignore the error if the filter does not result in an
actionable list of indices (ignore_empty_list) and exit cleanly.
options:
ignore_empty_list: True
timeout_override:
continue_if_exception: False
disable_action: False
filters:
- filtertype: pattern
kind: prefix
value: packetbeat-7.4.0-
exclude:
- filtertype: age
source: name
direction: older
timestring: '%Y.%m.%d'
unit: days
unit_count: 3
exclude:

yellow open packetbeat-7.4.0-2019.10.10-000002 E35rY8gsSwmtCIVynO6UwA 1 1 140115654 0 50.3gb 50.3gb
yellow open filebeat-7.2.0-2019.09.22-000003 KMLGoW2oTACXgGWFfNoiZw 1 1 35392252 0 33.8gb 33.8gb
yellow open packetbeat-7.4.0-2019.10.12-000004 2Qfcl9TfSjGaaZVESTXNww 1 1 141749339 0 50.1gb 50.1gb
yellow open filebeat-7.2.0-2019.10.22-000004 SszNt_e3SVyDxU0aPLnKZw 1 1 30526827 0 27.5gb 27.5gb
yellow open packetbeat-7.4.0-2019.10.08-000001 biESpWH4ReakGkGEEFeALA 1 1 138264429 0 50gb 50gb

As per my knowledge, till packetbeat-7.4.0-2019.10.10 curator reading after that -00002 didn't read by curator, i think.

Please help me with this.

**Comment by untergeek** [comment]
This is almost certainly because packetbeat 7.4, if connected directly to Elasticsearch, includes an ILM policy. If you can, why not use ILM to manage your packetbeat indices?

If you want to use Curator to manage these, however, then you need to tell Curator it’s okay to operate on indices associated with an ILM policy. Curator disables accidentally stepping on ILM-managed indices, by filtering them by default. You can tell Curator you want it to work on ILM-associated indices by setting the [`allow_ilm_indices`](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/ilm-and-curator.html) option.

**Comment by vasanthchellappa** [comment]
Hi Aaron.,
I am not familiar with the ILM, i will look into that and revert back if any queries with the same.

**Comment by vasanthchellappa** [comment]
Hi Aaron.,
Thank you so much. The following URL helped me to fix the issue
https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/option_allow_ilm.html
Enabled below option on packebeat.yml file.
options:
       allow_ilm_indices: true

The above fixed the issue and the indicies were removed with respect to retention period.
