### ISSUE TITLE
Add support to use alternative connection_class for curator

### ISSUE THREAD

**Issue by mmerrill3** [elastic/curator#1539]
We'd like the ability to use the default connection class, URLLib3HttpConnection, as opposed to the RequestsHTTPConnection.  There currently is no ability to override this in version 5.8.1.
We can enable a new option, or look at an environment variable PYTHON_CONNECTION_CLASS like the upstream elasticsearch client module does.

**Comment by untergeek** [comment]
Can you elaborate on what the benefit is here?

It's not merely a matter of adding an option to me. Initially, Curator was exclusively URLLib3 connected. Then came the AWS ES users who needed Requests because of `boto3`.  Then, encountering some issues with some of the actions and functionality, Curator was observed to be more consistent using Requests than URLLib3, so I dropped it in favor of Requests across the board.

So, there's some back story. Any change would effectively mean doubling up on testing to ensure that all actions work the same using URLLib3 as Requests.

**Comment by mmerrill3** [comment]
Hi @untergeek , thanks for the feedback.  The intention is to keep RequestsHTTPConnection as the default.  We have an environment where ES API calls are being proxied into AWS ES.  The proxy layer does the aws4auth signatures.  With versions greater than 5.7.6, we receive 403 errors from AWS.  So, we were looking for a way to revert back to to old URLLib3 class without having to change the code to do it for versions > 5.7.6.  

Our special setup may be due to IAM profiles, where curator is using the IAM profile for the EC2 device (which does not have permission to managed ES), but the proxy does have an IAM profile to manager ES.  It's like headers or some other attribute are being added by RequestsHTTP class that refer to the EC2 IAM profile, causing the 403.  

We are not setting any AWS settings for the curator configuration, so based on what we see, their should be no signature calculated by curator.  But, it is running on EC2 hardware, and there is some header being added that causes the upstream AWS ES cluster to throw a 403.  Remember, the proxy adds the signature, not curator itself. 

With versions <= 5.7.6 we don't see 403s while using URLLib3.  The differences between the two indicate that there has to be meta data added to the requests by HTTPRequests that is causing the upstream ES cluster to throw a 403, since URLLib3 doesn't add any headers.

**Comment by untergeek** [comment]
This is no longer possible with recent changes to the `elasticsearch` python module. Also, connecting to AWS Elasticsearch is moot as that is no longer in existence.
