### ISSUE TITLE
Helm Chart for Curator

### ISSUE THREAD

**Issue by mohsen0** [elastic/curator#1569]
As the `stable/elasticsearch-curator` is being deprecated, is there any plan to host his host in your own repositories?

https://github.com/helm/charts/tree/master/stable/elasticsearch-curator

I can see there is no docker image release.

**Comment by rafael-romero-carmona-claranet** [comment]
Hello @mohsen0 I found https://github.com/elastic/helm-charts/pull/961 and they said:
"[..] this is not something that we'll want to integrate in Elastic official charts.

Indeed, Elastic now recommends using ILM and SLM instead of Curator (see #236). Also, Elastic doesn't provide any official Curator Docker image for the reasons above and we stick to use only Docker images from Elastic in this charts."

**Comment by untergeek** [comment]
Curator is a labor of love project for me. Yes, it's hosted by Elastic, but I'm not paid to write or maintain it. It's "officialness" is therefore a bit of a conundrum. Yes, Elastic hosts the documentation, and the packages. But no, it's not likely to have "official" docker images or helm charts. I will see if I can host things in the repo, but that's about all I can do.

**Comment by untergeek** [comment]
For those wanting to maintain the Helm Chart for Curator on their own, I will continue to publish Docker images built on the Dockerfile in the root of this repository to my own repository: `untergeek/curator` on hub.docker.com — I just published `untergeek/curator:5.8.4` last night.

**Comment by ervikrant06** [comment]
yes basically changed command and args to something like below so that I can login into the POD after login I am running the command manually `/curator/curator --config /etc/es-curator/config.yml /etc/es-curator/action_file.yml`  it works fine without any issue. 

~~~
  - command: ["/bin/sh", "-c", "--"]
    args: [ "while true; do sleep 30; done;" ]
~~~

However running with passing args fails with error mentioned in latest comment for latest version. 

~~~
    args:
       - --config
       - /etc/es-curator/config.yml
       - /etc/es-curator/action_file.yml
~~~

**Comment by ervikrant06** [comment]
Able to fix it by overriding the ENTRYPOINT of docker image by simple bash wrapper. I don't know what difference it make but it works :-) 

~~~
FROM docker.io/untergeek/curator:5.8.4
COPY wrapper.sh .
ENTRYPOINT ["./wrapper.sh"]

cat wrapper.sh
#!/bin/sh
echo "Running startup script"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
/curator/curator "$@"
~~~

**Comment by untergeek** [comment]
Docker images are at Docker Hub, `untergeek/curator:TAG`
