### ISSUE TITLE
5.8.4 breaks support of Elasticsearch 5.6.16

### ISSUE THREAD

**Issue by Aohzan** [elastic/curator#1643]
5.8.4 version doesn't work with Elasticsearch 5.6

### Expected Behavior
In 5.8.3, curator works well with Elasticsearch 5.6.16

### Actual Behavior
After upgrade to 5.8.4, I have this error:
```
ERROR     Unable to connect to Elasticsearch cluster. Error: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```
Rollback to 5.8.3 works, but it's not possible on Debian 11.

### Steps to Reproduce the Problem
  1. apt install elasticsearch@5.6.16
  2. pip install elasticsearch-curator==5.8.4
  3. run curator

### Specifications

  - Version: 5.8.4 and Elasticsearch 5.6.16
  - Platform: Debian 10 and 11
  - Subsystem:

Thank you

**Comment by untergeek** [comment]
Curator 5.8.3 is the last version which officially supports Elasticsearch 5.6, which was released on September 11, 2017.

This is partly because it becomes too difficult to manage API changes spanning 3 major releases, and I needed to make a cut somewhere.

**Comment by Aohzan** [comment]
Ok I understand, but the 5.6.16 is supported in the changelog https://github.com/elastic/curator/releases/tag/v5.8.4, maybe you want to change this
thanks

**Comment by untergeek** [comment]
@Aohzan I apologize for the inconvenience. The problem is that `pip install elasticsearch-curator` will read from `setup.py` and/or `requirements.txt` which both specify `elasticsearch>=7.14.0,<8.0.0`, and there have been several releases since Curator 5.8.4 came out which have server test controls built-in, hence the error message. 

If you want to force Curator 5.8.4 to work with Elasticsearch 5.6 you'll have to manually downgrade the `elasticsearch` python module _after_ installation via pip.  The safe bet is to install `elasticsearch==7.12.1`, e.g. after installing Curator, run `pip install -U elasticsearch==7.12.1` to force-downgrade.

Your other alternative is to install [the Elastic-provided DEB package](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/apt-repository.html), which is frozen python code, and should have the older version of the `elasticsearch` python module. This self-contained distribution will not interfere with any python libraries in your environment.

**Comment by untergeek** [comment]
Of course, you could always still do `elasticsearch==7.14.0` if you wanted, but nothing really changed between 7.12 and 7.14, and that is a guaranteed to run version.
