### ISSUE TITLE
'indices' missing in stats dict

### ISSUE THREAD

**Issue by ttych** [elastic/curator#1670]
Hi,

https://github.com/elastic/curator/blob/7beab31e04c0788798d3e6e9e762ec69e6c86011/curator/indexlist.py#L125

In this code, in some situations the indices is not present in the stats dict,

leading to errors like : 
Failed to complete action: delete_indices.  <class 'KeyError'>: 'indices'

Could it be possible to protect this execution by adding a chunk of code like : 

```python
if 'indices' not in stats:
    return
```

Thanks,

Regards,

**Comment by untergeek** [comment]
I ask simply because the absence of stats will cause a different exception in other execution blocks where the stats are expected. I can't simply nope out here and expect the rest of Curator to function as expected. I need to know what's happening so I can _fully_ code around it.

It's either that, or I have to raise exceptions here and everywhere stats are expected but not found.

**Comment by untergeek** [comment]
With no further updates here, I'm going to close this. Feel free to re-open if you have more details surrounding the how and the why.
