### ISSUE TITLE
docker pull throws `missing signature key`

### ISSUE THREAD

**Issue by jbartak** [elastic/curator#1693]
## To submit a bug or report an issue

```
$ docker pull untergeek/curator:8.0.2
Trying to pull repository docker.io/untergeek/curator ... 
missing signature key
```

The same occurs for version `>=8.0.2` but actually works for versions `<8.0.2`

### Expected Behavior

Have this working.

### Actual Behavior

Not working `docker pull`

### Steps to Reproduce the Problem

  1. `docker pull untergeek/curator:8.0.2`.
  2. See the error message.

### Specifications

  - Version: `>=8.0.2`
  - Platform: `Centos 7`
  - Subsystem: `Docker version 1.13.1, build 7d71120/1.13.1`

**Comment by untergeek** [comment]
Duplicate issue of #1674.

This is a known issue with RHEL 7 and Centos 7 because of how old the provided version of Docker is. 

See #1674 for [more details](https://github.com/elastic/curator/issues/1674#issuecomment-1526801571), and a link to a [workaround gist](https://gist.github.com/untergeek/00dcb3f64cb0afa2f8fd194e9a5856d2).

Feel free to update the Python versions in the workaround (both what is used in pyenv and in the Dockerfile) to 3.11.5, and update the OpenSSL version to whatever is most recent.

**Comment by untergeek** [comment]
Oh, and the reason it doesn't work after 8.0.2 is because I had to update the Dockerfile and process to build both x86_64 and arm64 images and publish them in the same manifest. With the workaround, you will be making only an x86_64 image for your Centos box.
