### ISSUE TITLE
Weekly indicies

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/curator#181]
I've just started using weekly indices (Kibana speak [myindex-]GGGG.WW) with my ELK stack, but finding each component has a different idea of week numbers:

Kibana: http://momentjs.com/docs/#displaying/format/
Logstash: http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html
Curator: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

Would it be possible for curator to support the ISO8601 style week/year system, which is well defined and also what Kibana uses?

**Comment by untergeek** [comment]
This may be a 3.1 feature...

**Comment by Stono** [comment]
@untergeek I've trawled through threads and struggling to get my head around all of this, can you help?

I have an index built on {+xxxx.ww}, which gives me (for this week) syslog-2015.34

Can I use curator (3.2.3) to delete and indices older than 8 weeks?

I thought `curator --host 0.0.0.0 delete indices --older-than 8 --time-unit weeks --prefix syslog- --timestring '%Y.%w'` would work, but that actually deletes all indices regardless of date!

**Comment by Stono** [comment]
ok, needed %W

**Comment by untergeek** [comment]
This may be moot now with Curator 4 (alpha releases now available), because it simply counts the number of seconds in  `seconds`, `minutes`, `hours`, `days`, `weeks`, `months` or `years` from a point of reference.  Everything is converted to epoch time, and then it's just a matter of `older` or `younger` than the point of reference.  Curator is no longer trying to do complicated date math.

If you feel I'm closing this in error, feel free to open a new ticket, or re-open this one.
