### ISSUE TITLE
Documentation Issue: when deleting snapshots curator's exit status is non-zero if snapshots don't exist, but docs do not mention this or any other result codes.

### ISSUE THREAD

**Issue by dbeckham** [elastic/curator#294]
At first I thought this was just inconsistent behavior and was going to report it, but I checked the result code and curator returns `99` when no snapshots exist that meet snapshot criteria like `--older-than`.

Task runners and other tools like Cron or Rundeck look for a zero exit status. Programs that use exit status for more than just success or failure should document those statuses so that the tool can be used appropriately.

**Comment by untergeek** [comment]
Thanks for catching the omission. I intended to document this, but in the swarm of other things I neglected to do so.

**Comment by dbeckham** [comment]
Np, just wanted to let you guys know.  Along the same lines, I also noticed that the `delete snapshots --help` and `delete indices --help` output isn't really documented in the wiki, or displayed as a text block like the other --help options are.  Specifically, the `--repository` option and a couple of the generic flags for some of those commands are missing.

**Comment by untergeek** [comment]
I added a page on exit codes to the wiki: https://github.com/elastic/curator/wiki/Exit-Codes

I also added the command-line output to the wiki: 

- https://github.com/elastic/curator/wiki/index-selection
- https://github.com/elastic/curator/wiki/snapshot-selection

Since the wiki is user-editable, I'd love to have you contribute by adding the `--repository` and other flags.  Those were an omission on my part because of my haste to push out docs.  I merely copied the Index Selection page over and edited, but did not add the new stuff.

I will totally add you to the [CONTRIBUTORS](https://github.com/elastic/curator/blob/master/CONTRIBUTORS) if you do this for Curator.

**Comment by untergeek** [comment]
http://www.elastic.co/guide/en/elasticsearch/client/curator/current/snapshot.html
http://www.elastic.co/guide/en/elasticsearch/client/curator/current/exit-codes.html

Going to close this now, as documentation has been moved to the main Elastic documentation.
