### ISSUE TITLE
Filtering indices in 3.x

### ISSUE THREAD

**Issue by SegFaultAX** [elastic/curator#297]
Hello Curator Team!

I'm curious what the new pattern should be for selecting the set of indices to have actions applied via `curator.api`. Specifically, in 2.x, the iterative methods had an API like this:

```python
curator.delete(client, older_than=30, time_unit='days', prefix='logstash-')
```

But these API's have been pruned in 3.x, and I've found no alternative in the documentation. The examples only show cases where the set of indices to be closed/deleted/etc. are known ahead of time, but I haven't found any docs for getting that subset of indices directly from ES as in the older version. It appears that the "new" pattern may be to go directly through `regex_iterate`, but the usage of that is non-obvious and the documentation isn't very helpful. So I've started down the path of diving into the code to figure out how the cli module uses the filtering methods, but I'd like to know first if there is an official way to restore the original functionality without having to piece the internal API together myself.

Here's my REPL session from reverse-engineering it so far...

```python
>>> import elasticsearch, curator, re
>>> es = elasticsearch.Elasticsearch("REDACTED")
>>> indices = curator.get_indices(es)
>>> ls_indices = sorted(i for i in indices if i.startswith("logstash"))
>>> ls_indices
[u'logstash-1970.01.01', u'logstash-2015.02.28', u'logstash-2015.03.01', u'logstash-2015.03.02', u'logstash-2015.03.03', u'logstash-2015.03.04', u'logstash-2015.03.05', u'logstash-2015.03.06', u'logstash-2015.03.07', u'logstash-2015.03.08', u'logstash-2015.03.09', u'logstash-2015.03.10', u'logstash-2015.03.11', u'logstash-2015.03.12', u'logstash-2015.03.13']
>>> timestring = "%Y.%m.%d"
>>> time_regex = curator.get_date_regex(timestring)
>>> pattern = r"logstash-(?P<date>{})".format(time_regex)
>>> pattern
'logstash-(?P<date>\\d{4}\\.\\d{2}\\.\\d{2})'
>>> re.search(pattern, ls_indices[0]).groupdict()
{'date': u'1970.01.01'}
>>> curator.regex_iterate(ls_indices, pattern=pattern, groupname="date", timestring=timestring, time_unit="days", method="older_than", value=3)
[u'logstash-1970.01.01', u'logstash-2015.02.28', u'logstash-2015.03.01', u'logstash-2015.03.02', u'logstash-2015.03.03', u'logstash-2015.03.04', u'logstash-2015.03.05', u'logstash-2015.03.06', u'logstash-2015.03.07', u'logstash-2015.03.08', u'logstash-2015.03.09', u'logstash-2015.03.10']
```

Any insight or links to documentation I may have missed would be fantastic! Thank you so much for all your awesome work!

Edit: Cleaned up formatting of code snippet

**Comment by untergeek** [comment]
You are correct in your assessment that it is not well documented.  I shall have to explain this better.

Let me outline the process that happens now in 3.x. The flow is in [`index_selection.py`](https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py). Using the Click API, every argument/option is a decorator above the method.  Each of these decorators allows for a callback.  The callback for these options appends filters to an array (in the special context object: `ctx.obj['filters']`).  Once all of these filters are added, it then iterates through the list of filters against the working list of indices, sending the filter & current working list to the [`regex_iterate`](https://github.com/elastic/curator/blob/master/curator/api/filter.py#L20-L68) method.  This iteratively filters the list of indices in one method, rather than in each method as in v2.

Of course, the index_selection module has a _lot_ of if statements because there are a ton of edge cases.  I started with a considerably cleaner method, but the edge cases made it uglier.  I'd still rather have it ugly and working, though.

**Comment by SegFaultAX** [comment]
My assumption was (perhaps wrongly so) that anything in the cli namespace was not necessarily something you'd want to use as an API consumer (which I am in this case). Should the filtering logic in `index_selection.py` be lifted into the API so it's available to, and shared by, both use cases? How can I help with getting the API namespace up to the usability standards of 2.x? Perhaps for now we can include a subset of my REPL session above in the curator documentation so users trying to upgrade can get a feel for how they might fetch and filter the list of indices from their ES cluster?

In any case, I'm happy to contribute code/documentation/etc., but the current state of curator 3.x API is an upgrade blocker for me.

**Comment by untergeek** [comment]
That's actually a decent idea.  Since I'd be _adding_ API calls rather than deleting or altering them, I think this might work.  Let me think about how to accomplish this and get back to it.

**Comment by untergeek** [comment]
What would you like to see available in an API call?  What in the index_selection would you like to see separated?

**Comment by SegFaultAX** [comment]
Good question! The honest answer is, I don't know what the **full* API call should look like. But to get the ball rolling, we could break it down into several smaller filters that we chain together:

```python
es = elasticsearch.Elasticsearch("...")
indices = curator.get_indices(es)


logstash_indices = curator.filter.with_prefix(indices, "logstash-")
old_indices = curator.filter.older_than(logstash_indices, 3, "days")
```

Break it down into many small, easily composed functions to filter different aspects of the index names, rather than one massive monolithic filter. You could even create a class that makes composing multiple filters together natural. Here's a prototype I whipped together of what such a class could look like:

https://gist.github.com/SegFaultAX/cc6caa30136f213b5e12

Thoughts?

**Comment by untergeek** [comment]
I love it!  If I try to include this now, however, I worry about versioning, as the 3.0 API has been released, and this would result in a major overhaul of several components.  The only major change I had planned on making to the 3.0 API is renaming `regex_iterate` (an admittedly horrible choice of names) to `apply_filter`, and I'm only doing so because 3.0 was so recently released.  I _can_ add a similar `build_filter` method, though.

As a result--and to more closely mimic the CLI behavior--I put [this](https://gist.github.com/untergeek/8afb894eaa20298de9f9) together, and was prepared to release it alongside these [usage examples](https://gist.github.com/untergeek/a098f95fee70c8b7a4a1)

I would love to work toward something of this nature for 3.1 (at the earliest) or a 4.0 version in the future.

Thoughts?  Do you think the potentially breaking nature of this worth pursuing for a rapid 3.0.1 release?

**Comment by SegFaultAX** [comment]
Well, the proposed changes are purely additive in nature (relying partially on the existing API functionality). As such I'm not sure there is too much risk of it breaking anything. Your proposal seems to work along a similar axis (interesting how close our solutions ended up being), although you seem to be favoring the larger monolithic function to apply filters + a "filter builder" function. I guess my main feedback about that would be it drastically increases the complexity of the API since it's all coalesced under one function. But it's purely a stylistic thing. :)

I totally get your concern with not introducing breaking changes, but I think if we do it right, we can make the changes purely additive in nature. Whatever your decision for the implementation style, I'm excited to have **some** working solution in place for this. Thank you again for your time and effort!

**Comment by untergeek** [comment]
The more I think about this the wider the pendulum swings in both directions.

I really like the simplicity of the Class/Object, but its complexity grows quickly if you do not specify default values.  I do not want any default values.  This is one of the reasons for the endless `if` statements in `index_selection` and the associated methods.  I want fairly strident controls forcing the user to specify things like `days`, and `timestring`.  If I'm already going to have that, as complex as it is, it makes some sense to keep the formatting the way it is.  I also want to have the process mimic the way the CLI is filtering (callbacks are adding the filters one at a time), which is slightly different from how the class handles it (and I suppose you could have the class instance be part of the obj dictionary, but that's a future discussion).

On the other hand, it makes some sense to add the other method as an alternative way to add items.  It's clean, it's simple, and many users may wind up preferring it.

So, rather than choose one or the other, **why not both?**  There's no reason not to have both!  Use the API call that you like.

Because it so closely mimics the way the command-line works, I'm including the `build_filter` method as shown, including the examples.  

In addition, I would absolutely *love* for you, @SegFaultAX, to add this class as an alternative method to add index filters, complete with defaults as you have them.  Please add the unit tests in the appropriate files.  I definitely want to keep the 99% code coverage the project currently has.  Please also thoroughly document the class such that sphinx will pick it up.  We can go over any and all changes before merging.

In this way I hope we can pave a way for the future, while over-filling the needs of the present.
