### ISSUE TITLE
include_global_state is always true

### ISSUE THREAD

**Issue by simmel** [elastic/curator#303]
When taking snapshots it looks like `include_global_state` is [by default set](https://github.com/elastic/curator/blob/e60394da9ba9d6d32931b0bd61df941d8df194e9/curator/cli/snapshot.py#L11) to `True` and it the [option just allows to set](https://github.com/elastic/curator/blob/e60394da9ba9d6d32931b0bd61df941d8df194e9/curator/cli/snapshot.py#L25-L26) it to `True` and that makes no sense.

Either it's off by default or the option sets it to off.

**Comment by untergeek** [comment]
Thanks for bringing this to my attention.  What is really going on is that [this](https://github.com/elastic/curator/blob/e60394da9ba9d6d32931b0bd61df941d8df194e9/curator/cli/snapshot.py#L11) is not used.  It's a carry-over from Curator 2.x.  The [`is_flag`](https://github.com/elastic/curator/blob/e60394da9ba9d6d32931b0bd61df941d8df194e9/curator/cli/snapshot.py#L25-L26) option makes this `True` if set.

However, it makes sense to change this to follow the pattern shown for [`--wait-for-completion`](https://github.com/elastic/curator/blob/e60394da9ba9d6d32931b0bd61df941d8df194e9/curator/cli/snapshot.py#L20-L22), since `include_global_state` _should_ be `True` by default.

It can be further cleaned up as `default=DEFAULT_ARGS['ignore_unavailable']` is not needed either.
