### ISSUE TITLE
es_repo_mgr cli is ignoring parent options for create sub-command

### ISSUE THREAD

**Issue by feltnerm** [elastic/curator#336]
Either I'm doing something silly, or `click`/`es_repo_mgr` is not passing parent command command-line options to the `create` sub-command.

I was able to validate this by simply putting `print('connecting...', kwargs)` on [utils.py#L105](https://github.com/elastic/curator/blob/89e84f960b0188e6dd38dd48d66a4a67a4bb66dc/curator/cli/utils.py#L105).

Success with `show` command:
```
% es_repo_mgr --host foobar show                                                                                                                                             
('connecting...', {'url_prefix': u'', 'http_auth': None, 'loglevel': u'INFO', 'host': u'foobar', 'logformat': u'default', 'timeout': 30, 'debug': False, 'use_ssl': False, 'logfile': None, 'port': 9200})
```

Error with `create` command:

```
% es_repo_mgr --host foobar create fs --repository foo --location /tmp/foo
('connecting...', {})
```

I'm not familiar enough with the `click` library to tell if maybe someone just misconfigured it, but I know enough about python to be dangerous. Let me know if you need more info, or if I can help otherwise.

**Comment by untergeek** [comment]
The `--debug` flag will show you the [same thing](https://github.com/elastic/curator/blob/89e84f960b0188e6dd38dd48d66a4a67a4bb66dc/curator/cli/utils.py#L102) without having to edit the code. 

I think the problem is that I have the wrong level of `ctx` in the `fs` and `s3` methods.

Try changing:
```
client = get_client(**ctx.parent.params)
```
on [line 149](https://github.com/elastic/curator/blob/89e84f960b0188e6dd38dd48d66a4a67a4bb66dc/curator/cli/es_repo_mgr.py#L149) to
```
client = get_client(**ctx.parent.parent.params)
```
That should pass the variables through properly.

**Comment by untergeek** [comment]
That's in `curator/cli/es_repo_mgr.py`, by the way.

**Comment by feltnerm** [comment]
That appears to have worked. Submitted a PR for your review.
