### ISSUE TITLE
Curator install from source error

### ISSUE THREAD

**Issue by ramreddy26** [elastic/curator#354]
Hi, I installed curator using  the pip installation from source method
http://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html

But I am getting below error when I ran curator, I am getting below error
Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: click>=3.3

Also I tried running python /usr/lib/python2.6/site-packages/curator/curator.py -v and got below error

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/curator/curator.py", line 2, in <module>
    from .cli import cli
ValueError: Attempted relative import in non-package

I have python 2.6 version, pip 6.1.1 and curator 3.0.3 version. Please let me know how to fix this issue.

**Comment by untergeek** [comment]
## Dependency issue?

> raise DistributionNotFound(req) pkg_resources.DistributionNotFound: click>=3.3

This indicates that the `click` dependency did not get installed.  If it did, and this error is still happening, you'll probably have to upgrade `setuptools`.

## Upgrade setuptools

I also see that you're using python 2.6.  It is often necessary is to install the latest version of setuptools when running python 2.6.  See https://github.com/elastic/curator/issues/56#issuecomment-77843587 for more details there.

You will have to download the most recent version of setuptools if you're doing this manually.  I do not know if there are other dependencies it will need.

## Launching as a module

In versions prior to v3, you could execute the `curator.py` file as a script. Because Curator is now a proper python package, the only way to launch Curator v3 is via the entry_point or as a module.  

The entry_point typically gets installed into `/usr/bin` or `/usr/local/bin` as `curator`--which you tried running first.  The other way to make it run is to call it as a python module:

    python -m curator

This will execute as though you called the entry_point, but the command-line help will show this oddity:

    Usage: __main__.py [OPTIONS] COMMAND [ARGS]...

Note the `__main__.py`.  This is because you called the module with no other instructions, so it called `main`.

**Comment by ramreddy26** [comment]
Thank you, upgrading setup tools fixed the issue. Thanks for your prompt reply :+1:

**Comment by untergeek** [comment]
See [the new FAQ](http://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html)
