### ISSUE TITLE
curator not deleting indices

### ISSUE THREAD

**Issue by rtkmhart** [elastic/curator#365]
I'm using curator 3.0.3 on ES 1.5.1. curator is not deleting time-based indices when given a regexp. Indice names have the pattern "observations-<id>-YYYY.MM.DD". Let's use 'observations-xyz-2014.01.01' as an example (id changed to protect the innocent, but it's a real index). Command line is as follows:

```
/usr/local/bin/curator --debug --timeout 3600 --logfile /tmp/curator.log delete indices --regex observations-.* --older-than 40 --time-unit days --timestring %Y.%m.%d
```

In the log I see these lines (truncated lines because is trying to delete all the indexes from January 1 to 40 days ago):

```
2015-04-23 13:48:57,548 DEBUG     curator.cli.index_selection                indices:101  ACTION: delete. INDICES: [u'observations-xyz-2015.01.01', ... ]
2015-04-23 13:48:57,548 DEBUG         urllib3.util.retry               from_int:155  Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-04-23 13:49:58,403 DEBUG     urllib3.connectionpool          _make_request:383  "DELETE /observations-xyz-2015.01.01,... HTTP/1.1" 200 21
2015-04-23 13:49:58,404 INFO               elasticsearch    log_request_success:62   DELETE http://localhost:9200/observations-xyz-2015.01.01, ... [status:200 request:60.856s]
2015-04-23 13:49:58,404 DEBUG              elasticsearch    log_request_success:64   > None
2015-04-23 13:49:58,404 DEBUG              elasticsearch    log_request_success:65   < {"acknowledged":true}
2015-04-23 13:49:58,404 INFO         elasticsearch.trace    log_request_success:72   curl -XDELETE 'http://localhost:9200/observations-xyz-2015.01.01,...?pretty' -d ''
2015-04-23 13:49:58,404 DEBUG        elasticsearch.trace    log_request_success:75   #[200] (60.856s)
#{
#  "acknowledged": true
#}
2015-04-23 13:49:58,404 INFO           curator.cli.utils               exit_msg:60   Job completed successfully.
```

But the indices aren't actually deleted.

Any ideas?

**Comment by untergeek** [comment]
Weird.  That seems more like an Elasticsearch issue than a Curator one.  Clearly it is matching the indices properly, and sending the DELETE properly, and getting an acknowledged.

Whats' in the Elasticsearch logs at that same time?

**Comment by untergeek** [comment]
Hmmm.  The other issue is this:

> `log_request_success:75   #[200] (60.856s)`

It's taking almost exactly 60 seconds to perform a delete.  This seems quite high.  How many indices are there?  How busy is the cluster?  Perhaps something is timing out on the other end.

**Comment by rtkmhart** [comment]
Thanks for the quick response!

We're at around 1250 indices on 20 data nodes, the cluster is very busy. There are no errors in logs on the master or data nodes that I can find.

What's weird is I set the --timeout to 3600, which I'm assuming is seconds... but it comes back in 60 seconds, consistently across a few runs. Is there another timeout somewhere that's not getting overridden by the 3600?

**Comment by rtkmhart** [comment]
It's definitely a timeout issue somewhere. If I set --older-than to something much higher so it's only deleting 10 indices at a time, it comes back in around 30 seconds and has successfully deleted the indices.

**Comment by untergeek** [comment]
You may be hitting this FAQ item:

http://www.elastic.co/guide/en/elasticsearch/client/curator/current/_q_snapshots_seem_to_be_working_why_am_i_getting_literal_snapshotmissingexception_literal_messages.html

**Comment by untergeek** [comment]
Do you have a load balancer in front of your client nodes?

**Comment by rtkmhart** [comment]
No load balancer, I'm running curator directly on the master node talking to localhost:9200.

**Comment by untergeek** [comment]
This timeout is not from Curator or Elasticsearch, or you'd see the error in both sets of logs.  Do you see anything in the Elasticsearch logs?

Is there a proxy or a gateway of some kind?  A firewall that will only keep state with a 60 second timeout?

**Comment by rtkmhart** [comment]
There is nothing in the Elasticsearch logs, I've double checked it now.

There is no proxy or gateway of firewall in the path. I'm running curator directly on the same host as the master node, connecting to localhost:9200, and all data nodes are running in the same subnet without any firewalls.

What's even weirder is that now it's returning consistently in 31 seconds without actually doing anything. I haven't changed anything except to keep running the same command (posted in the initial comment) over and over again, pushing the definition of insanity. :)

**Comment by untergeek** [comment]
Whatever else may be going on, your Elasticsearch cluster is overloaded.  It should never take even 30 seconds to delete a batch of indices.  You may simply be suffering from master/client node communication timeouts (though I'm surprised there's not logs to indicate such) due to the overloaded nature of your cluster. 1250 indices, presuming the default 5+1 shard count, divided among 20 nodes is 625 shards per node, which is a rather high number.  By default, Elasticsearch allocates 10% of the heap it gets to index caching and management. Each active shard will want 250M of that 10%, and each inactive shard will want 4M of that 10%.  Even if you had zero active shards across your nodes, 625*4M = 2.5GB of that 10%.  That would suggest you would need 31G heaps on each node (10% would be 3.1G).  If you are not using 31G heaps, you are possibly putting a high amount of memory pressure on the index cache.  Elasticsearch will try to be smart about how it handles this memory.  A shard becomes inactive 30 minutes after the last indexing activity.  Elasticsearch can probably squeeze the memory down to about 47M per active shard (though indexing performance is degraded) and just under 1M for inactive shards.  When Elasticsearch can't squeeze that memory any more, it will suddenly, and without warning, stop being able to index new data.  The cluster will still be up, and search will still work.  You just won't be able to index any more.  This typically only happens in time-series index situations as shard count per node becomes an issue.

Also of concern, with regard to shard count per node, is that deleting indices will result in a massive cluster rebalance.  Elasticsearch, by default, will try to keep a similar number of shards per node.  If you delete a bunch in a big batch, it will try to rebalance, which could also result in severely degraded disk and network I/O.

You may simply have to try pruning your indices in much smaller batches and wait for the cluster to recover in between.

**Comment by rtkmhart** [comment]
We're having similar discussions about cluster state with our support rep at Elastic :) Our current cluster state is around 250Mb. While the cluster is big, it's still dealing with what we're throwing at it. 

We have some design changes coming, but in the meantime we have to deal with it. For the record, 1250 indices and 7778 shards. Masters have 4GB heap, and according to Marvel are not under any sort of duress, GC drops heap usage to 25% and CPU usage < 25%. 

So while that may be big by some measure, it still doesn't really explain why this isn't working.

I did notice that at some point curator splits the total number of indices to delete into smaller chunks (if memory serves, been a long day). Is that configurable? That is, can we tell curator not to try to delete more than say 10 in one batch?

**Comment by untergeek** [comment]
Just because the masters aren't overloaded doesn't mean that there isn't a heavy load on the network and disk I/O with shard shuffling.  You're still trying to remove some 73 indices at once. Deleting all primary and replica shards for that many indices in a single batch is going to cause a lot of cluster updating, and you already have a 250Mb cluster state.  Sending updates for that much is not going to be easy.  While your masters may not be taxed, consider how much data has to move with that update, between the master and every other node.  That's a lot of traffic and updating!

Curator's batching is not configurable.  It's there to defeat the 4k URL limit imposed by Elasticsearch.

At the bottom of all of this, the reality is that the problem isn't Curator's, but Elasticsearch's.  Curator simply sends the command

**Comment by untergeek** [comment]
(and the command is getting there intact).

**Comment by rtkmhart** [comment]
It turns out we have a mapping problem (bug in our code) that's causing our massive cluster state, we're in the process of cleaning it up. Curator seems happy again. Thanks for your help and advice!
