### ISSUE TITLE
Option to save (delete) snapshots by age-grouping

### ISSUE THREAD

**Issue by wkoot** [elastic/curator#373]
I have a cronjob taking snapshots of an ES cluster every 20 minutes.
This leads to a very large amount of snapshots, clogging up the repository if I don't clean up regularly.
Currently I'm just deleting everything older than 50 hours, but I'd also like to keep some older generations.

Example:
- Save 5 backups from the past 2 hours
- Save 1 backup per hour for time >2h && <12h
- Save 1 backup per day for time >12h && <7d
- Save 1 backup per week for time >7d && <30d
- Delete everything older than 1 month

Since it might be overly (and uselessly) complex to provide such a set of rules on the commandline, something like an exponential save function (a la exponential backoff) would suffice.
For instance, BackupPC has fairly straightforward machinery to support this: http://backuppc.sourceforge.net/faq/BackupPC.html#_conf_fullkeepcnt_

**Comment by untergeek** [comment]
Lucene works by lumping segments into logical groupings called indices.  Elasticsearch extends this by calling a lucene index a "shard," and then logically groups those into "indices."  A segment is completely immutable when written.  Lucene automatically merges segments into bigger segments.  The "optimize" call is actually a forceMerge operation.

Snapshots are collections of segments, nothing more.  If a segment hasn't changed since the last snapshot, the new snapshot only points to the existing segment.  No segment which is referenced by a "newer" snapshot will be deleted when you delete an "older" snapshot.

In this sense, snapshots are not a typical backup.  You're far better off naming snapshots accordingly:

* 20 minute intervals could be named: rapid-TIMESTAMP
* hourly-TIMESTAMP
* daily-TIMESTAMP
* weekly-TIMESTAMP

Curator would handle these easily, now that you have a varied approach.

* Keep no more than 2 hours of the rapid-TIMESTAMP snapshots
* Keep no more than 12 hours of hourly-TIMESTAMP
* Keep no more than 7 days of daily-TIMESTAMP
* Keep no more than 30 days (or 28) of weekly-TIMESTAMP

In this way, you'll have an easy to read set of snapshots, recognizable by name, and an easy way to keep retention organized.  And fewer segments will be redundant at this point, as the more "merged" segments will tend to percolate up, especially if you use Curator's optimize to forceMerge segments on "older" indices for the weekly or daily snapshots.

**Comment by wkoot** [comment]
Yes exactly. I know how Lucene and ES work, but having a few hundred snapshots severely slows down the snapshots endpoint.
Running named snapshots could be an option, but it would be a bit messy to administer. I guess I could add a suffix with the timespec though.

**Comment by untergeek** [comment]
I totally understand that with snapshot count.  

Since snapshots are just Lucene segment copies, I do recommend named snapshots.  The current version of Curator does make it "messier," but the results are very clean and manageable.

**Comment by wkoot** [comment]
Oh, one part isn't covered by the config you suggested: this will not ensure at least X snapshots for a given timespan. What I mean is that curator will delete anything that is older than Y, although I would never want it to throw away every snapshot. Any idea?

**Comment by untergeek** [comment]
The --exclude flag will allow you to exclude snapshots.  It's not deterministic, but it would allow you to preserve certain snapshots.

**Comment by wkoot** [comment]
The use case of the snapshots is "something got fucked up, I want to roll back to before the fuckup". But if the fuckup happened 1 hour ago, you'll restore a different snapshot than if it happened 5 days ago (i.e. most recent not-broken data). So you want to have a high density of snapshots that spans back for quite some time.

Because lots snapshots hardly give (disk) overhead (i.e. because of Lucene segments), the simple but stupid approach was to store shitloads of snapshots. That is however out of the question because it makes the entire ES cluster slow whenever a snapshot is started (which, being every 20 min, basically means the entire time).

So I need to find a way to *keep* generations of snapshots easily. I can't hardcode to exclude a certain snapshot because the relevancy is subject to a sliding window. That would require a wrapper that lists all snapshots and then finds out which ones to keep, ergo what to pass to `--exclude`.

I understand your suggestion, but it seems more convenient to put this into a parameter instead of a wrapper around `--exclude`. Just like there is `--disk-space` which recursively "keeps" snapshots until a certain counter is out of bounds?

**Comment by untergeek** [comment]
That's why tiered, named snapshots is my recommendation.  If both `rapid-TIMESTAMP` and `hourly-TIMESTAMP` refer to some of the same segments, then those segments will be referenced by a restore, even if `rapid-TIMESTAMP` is deleted later on.  This is both the blessing and the curse of snapshots.  The more you have, the more segment pointer checks have to be made, but the less storage space you consume, and the less network/shared-disk-i/o you have to worry about.

I will try to add an exponential backoff feature, but it won't be available for a bit.

**Comment by untergeek** [comment]
In analyzing what would need to be changed to permit this at the CLI level, it will either be a breaking change, or I will have to create another "delete" sub-command.  Currently the delete subcommands are `indices` and `snapshots`.  Adding another sub-command, like "snapshots-tiered," will be a bit odd and confusing, but I may still do it.  I also may opt not to, as it will be short-lived and removed when 4.0 comes out.

4.0 will have some major new features, like file-based configuration, which will make something like this easier.

**Comment by untergeek** [comment]
I'm not sure this is necessary any more, since Elasticsearch 2.x improved the slowdown that used to occur when there were many snapshots in the repository.

I'm going to close it.  If someone still wants this feature, they can make a new issue, or reopen this one.
