### ISSUE TITLE
Error:Failed to verify all nodes have repository access  why?

### ISSUE THREAD

**Issue by LiangAllen** [elastic/curator#388]
execute
curator --http_auth admin:123456 --timeout 21600  snapshot  --repository logsnapshot indices --older-than 3 --time-unit days --timestring %Y.%m.%d

INFO      Job starting: snapshot indices
ERROR     Failed to verify all nodes have repository access.
WARNING   Job did not complete successfully.

curator, version 3.0.3
elasticsearch v1.5.0

**Comment by untergeek** [comment]
Starting in version 1.4 of Elasticsearch, there's an internal test—which is accessed by this API—that verifies that _all_ nodes of the cluster have write access to the snapshot repository.  Curator uses this to prevent you from attempting a snapshot which would have automatically been `PARTIAL` (because not all nodes could write to the shared repository).

What kind of repository are you using?  `fs`? `s3`?

**Comment by LiangAllen** [comment]
Thank you, It has been working, it may be a configuration error

**Comment by untergeek** [comment]
Or possibly that one of the nodes temporarily was unable to read/write to the shared filesystem.

Can you close this if you're satisfied?

**Comment by LiangAllen** [comment]
OK At first I think it is my version of the problem, but now this command has been executed successfully, I found my nfs configuration  problems, thank you very much
