### ISSUE TITLE
Provide Curator package downloads with each release

### ISSUE THREAD

**Issue by peterskim12** [elastic/curator#395]
I've been emailing with @untergeek on the side about this but wanted to create this issue just to make sure it's tracked.

It'd be great if each Curator release is made available in various popular packaging formats. Perhaps just the same ones that Elasticsearch is available in (.tar, .zip, .deb and .rpm).

Thanks!

**Comment by pickypg** [comment]
Also releasing a `.exe` variant would be super handy to hide all of the nuisances of installing Python in some Windows environments.

**Comment by untergeek** [comment]
@pickypg I am already doing that one.  We should make them available through our regular download channels, though.

**Comment by pickypg** [comment]
@untergeek That's what I meant. :+1: I remembered that you were making them :).

**Comment by tigryss** [comment]
+10

**Comment by tigryss** [comment]
@untergeek: can i help somehow? kann ich mal dich unterstützen irgendwie?

**Comment by untergeek** [comment]
.deb and .rpm are not going to happen soon.  They just won't.  I spent days working on making prototypes, and while I can make debs that _would_ be installable, they depend on the other dependencies being turned into packages as well: elasticsearch-py (the official elasticsearch python module), click (the CLI library module), and urllib3.

I think we could make elasticsearch-py into a module in-house, and add it to our repository, and a sufficient urllib3 is probably already available.  Click, however, is the problem.  I don't own that project, and I don't want to become responsible for the upkeep of RPM/DEB versions of Click for RedHat/CentOS, or Debian/Ubuntu, etc.  And without a Click package, there can be no Curator package.  Bundling their source inside the package is a big no-no, so that won't work either.

**Comment by untergeek** [comment]
The officially recommended way to install Curator will remain `pip install elasticsearch-curator` for the time being.

However, I can use [nuitka](http://nuitka.net) to compile Curator and its dependencies into bytecode, and then share those as .tar.gz and .zip (for windows).  The problem with this approach is that it is _extremely_ system dependent, as it bundles the libc and other libraries from the host system.  I have built Docker images which will create Curator binaries for Ubuntu 12.04 & 14.04, CentOS 6 & 7 (latest on each).  The resulting binaries will work on the system they came from, but are not necessarily guaranteed to work on minor versions in the RHEL/CentOS camp.  It would be trivial to make another image for those point versions, however, now that I have good Dockerfiles and scripts.  

We can make these binaries available for download through our regular channels.  While it _might_ be possible to make RPM/DEB packages of these tarballs, because the binary is _so_ system specific, I don't think that's a wise approach.  Too many possibilities of library conflicts.  It would lead to major headaches in attempting to guarantee compatibility which are easily rectified by building a new binary from a compatible Docker image.

**Comment by untergeek** [comment]
Some digging has shown that only unstable and very current builds for Debian and Ubuntu have python-click (or worse, python-click-cli, causing a name conflict with the dependencies), and they're a major point version behind current, though 3.3 should still work with Curator.

**Comment by untergeek** [comment]
We _could_—at least there's nothing technical stopping us—host our own "Curator PPA" (or yum repository) and include our own build of Click.  That's a discussion that needs to happen internally, though, as there are licensing and security considerations.  If we do go that route, it may not even "fix" the issue users are having where they are in an air-gapped datacenter and wouldn't be able to download from the PPA directly.  They'd need 3 or 4 RPM/DEB packages to complete the install, rather than one pretty RPM/DEB.

**Comment by untergeek** [comment]
I have proof-of-concept (well, they actually work rather well) DEB packages for python2/3 on Debian/Ubuntu.  The problem is that it starts getting sticky rather quickly.  These were all built using @jordansissel's remarkable [fpm](https://github.com/jordansissel/fpm)

### Required
* python-click_4.0_all.deb
* python-elasticsearch_1.6.0_all.deb
* python-elasticsearch-curator_3.1.0_all.deb

### Dependencies (if necessary)
* python-setuptools_18.0.1_all.deb
* python-urllib3_1.10.4_all.deb

### Optional (for HTTPS certificate verification)
* python-certifi_2015.04.28_all.deb

**Comment by untergeek** [comment]
@pickypg @peterskim12 See if these options satisfy you: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html

**Comment by pickypg** [comment]
@untergeek Very satisfied. Thanks!

**Comment by peterskim12** [comment]
This is great @untergeek! Thanks for working through all the issues to make this a reality. Will be super-helpful to the non-Python folks out there.

**Comment by untergeek** [comment]
Yay!
