### ISSUE TITLE
curator v3.2.0 reporting successful indices deletion, but does not actually deleted them

### ISSUE THREAD

**Issue by TinLe** [elastic/curator#420]
I have a cluster with bunch of old indices that I want to prune, keeping only latest 7 days.  I run the command.

$ curator --port 9217 --timeout 900 delete indices --timestring "%Y.%m.%d" --older-than 7 --time-unit days
2015-06-25 16:54:49,038 INFO      Job starting: delete indices
2015-06-25 16:54:49,628 INFO      Pruning Kibana-related indices to prevent accidental deletion.
2015-06-25 16:54:49,628 WARNING   Very large list of indices.  Breaking it up into smaller chunks.
2015-06-25 16:54:49,629 INFO      Deleting indices as a batch operation:
.....bunch of outputs
2015-06-25 16:55:33,241 INFO      Job completed successfully.

But that is not true.   I checked and there are still many indices that were supposed to be deleted and were not.   So if I run the same command multiple times, eventually all the indices get deleted.

The output of multiple runs is fairly long, I'll put them in a gist here:
https://gist.github.com/TinLe/c64dbe495e0c2d228a6b

The last few runs correctly gave Error or Warnings, so that part is correct.   The error/warning were because the cluster just started creating new daily indices, so were busy with initializing shards (yellow status).   Once the cluster got done with the new indices, the deletion completed fine.   When I started the deletion, the cluster was relatively quiet and in green status.

The bug is that curator is reporting "Job completed successfully" when obviously that is not the case.

**Comment by untergeek** [comment]
I appreciate that this is a bug for you.  This is _extremely_ unusual, except in cases where the cluster is heavily overburdened.  The `delete` API call [checks for exceptions](https://github.com/elastic/curator/blob/master/curator/api/delete.py#L16-L24), and if there are none, it returns True.  This is why it's considered a successful operation.  Elasticsearch itself is capable of deleting hundreds of indices simultaneously when not under egregious loads.  The test suite itself does this with many indices simultaneously.  If your cluster is failing to do this, you should look at the Elasticsearch logs to see what's happening.  Even the time elapsed in the log you provided suggests it sent all of the deletes in a 2 second window.

What happens if you run this with the `--debug` flag?  If you're trying to delete older than 7 days, why are you waiting until there are 5 indices of every kind, rather than running daily to prune the number of indices more regularly?  How many nodes in your cluster?  How many shards per node?  The count of indices you have is concerning and could be a contributing factor.

**Comment by untergeek** [comment]
Please attach or link any corresponding Elasticsearch node logs.  The client you connected to on port 9217 is the most important, but all others need to be looked at.

Why 9217, by the way?  Are you really running 18 or more local nodes so the number is bumped?

**Comment by untergeek** [comment]
I count 94 indices you're trying to delete at once.  This translates into 940 shards, at the default 5+1.  The first pass is 66 indices, which would be 660 shards at the default 5+1.

Is 5+1 your index template?  Or are you creating these with more or fewer shards/replicas?

**Comment by TinLe** [comment]
Our retention policy is 31 days and we have plenty of disk space for the indices.  This particular cluster contain wrong indices settings and index mappings for the older (more than 7 days ago), so I was removing those in preparation for re-indexing.

The cluster is actually running on normal port 9200.   I am port forwarding to the cluster in production via a bastion host via port 9217 on my desktop (so, desktop:9217 --> production:9200).

None of the indices have replicas, but the number of shards for the indices are different depening on their  expected daily size (in order to keep shard size less than 45GB if possible).   So number of shards is between 3 to 40 per daily index (we have indices that hovers around 3+ TB daily).

I didn't use the --debug flag, but I will do so next time.   I have other similar clusters in other datacenters that I need to do cleanup on, so I'll have more data for you.

**Comment by untergeek** [comment]
Disk space is only part of the equation.  It's actually the least important part.  Each shard in Elasticsearch comes with a management cost.  The master node(s) have to ensure that all nodes keep a current cluster state.  The index cache portion defaults to 10% of the allocated heap.  Each active shard wants 250MB of that 10%, and each inactive shard wants 4M, and you have some indices with 40+0 shards. If a node cannot keep all of the shards in the 10% with these values, it begins to compress them.  This compression slows down indexing and is tied to overburdening of the cluster.  In fact, with too many shards per index, I've seen those values compressed to the point that there was only 47M of cache available for each active shard and 750K for each inactive shard.  At or around that point, Elasticsearch stopped indexing outright, though search still worked.

This is why I asked how many nodes you have, and how many shards per node.  Also important to add to the equation is how big your heap is on each node.  The sheer number of indices and shards you have could be leading to this pain point.

**Comment by TinLe** [comment]
I agree with too many shards is not good.   This is also part of the reason I am doing cleanup on this particular cluster.   I've migrated the large indices off and keeping the max number of shards to 8+0 for the larger indices, the rest are kept at 3+0.    This cluster has been stable and working fine for several months now.  Even with the larger indices on it.   I am moving them off to help distribute the load and increase performance.

With all that said...   Instead of reporting deletion OK, perhaps curator can say that deletion has been queued OK, but to check later to confirm.   That would seem to be more accurate.   All of my maintenance are done via scripts, but if my scripts can not trust the results curator is returning, it would be a problem.

It explains why some of my clusters are running out of disk space even with maintenance script running nightly.   I have now added in a loop to run script 10 times or until curator report there is no matching indices to ensure that the indices are deleted.

**Comment by untergeek** [comment]
How big is your cluster state?  (`curl -XGET 'http://localhost:9200/_cluster/state'`, then check how big the resulting file is). With so many indices (and shards), and each having their own types & mappings, it could be quite large.  Trying to keep such a large cluster state in sync between all of your nodes could be contributing to the problem.

Adding a verification step is possible, but tedious.  I hesitate to add verifications to things for edge cases like this where your cluster state is likely a contributing factor.

**Comment by TinLe** [comment]
I get 900K size for cluster state.

$ curl -s -XGET 'http://localhost:9200/_cluster/state?pretty' > /tmp/state.json
$ ls -la /tmp/state.json
-rw-r--r-- 1 tin user 953142 Jun 26 18:32 /tmp/state.json

**Comment by untergeek** [comment]
How many nodes, and what is the heap size?

**Comment by TinLe** [comment]
30 nodes (64G RAM), maxheap is 24G.   My monitoring system tells me on average, they use around 9G, peaking to 16G before GC kicks in.

**Comment by untergeek** [comment]
What's the disk I/O at?  How many shards per node?

**Comment by untergeek** [comment]
Also, how many master nodes?

**Comment by untergeek** [comment]
You can also try the code change in #423 to see if that works for you.  This is a work-around for an edge case.  Elasticsearch should _never_ fail in this way.  Something in your cluster is not right.

**Comment by TinLe** [comment]
I have 16x1TB SAS drives.  14 are in RAID6 for data, 2 in RAID1 for boot, root, /home.

I/O on RAID6 volume is:
Read: max: 1.65MB, avg:160KB   (ops: max: 33.25/s, avg: 3.27/s)
Write: max: 8.8MB, avg: 6.44MB   (ops: max: 2.14K/s, avg: 1.57k/s)

Average is 16 shards per node, total of 479 shards across 30 nodes.

**Comment by untergeek** [comment]
Each box has 16 drives?  RAID6 is certainly not known for its write speed, regardless of how underutilized it may appear.  For an indexing heavy operation (which yours appears to be, based on the writes), this would appear to be an interesting choice.  Is that to mitigate the absence of replica shards?

**Comment by TinLe** [comment]
I tried https://github.com/elastic/curator/pull/423 and it does seem to work.   I'll do some more testing to see how it does on all my clusters.

Yes, RAID6 is partially for mitigating not using replica and also because we wanted storage size.

**Comment by untergeek** [comment]
@TinLe any news on this?

**Comment by TinLe** [comment]
I've been out of office, just got back yesterday.   Still catching up on 1
week's worth of email :-(.   I'll update this thread asap.



On Tue, Jul 14, 2015 at 9:20 AM, Aaron Mildenstein <notifications@github.com

**Comment by trevorjwilliams** [comment]
I may have some insight here, having just run into the issue myself, and it doesn't require a massively-overloaded server.

With Curator's switchover to using the bulk API instead of acting on individual indices, operations, such as the bulk deletion of a bunch of huge indices, will take place over a single long-lived request, which can timeout.  Bumping up the --timeout option fixes this on the client side... but not on the server side.  I executed a bulk deletion via Curator while tailing the master node's logs, and saw this:

```
[2015-07-16 14:10:49,269][INFO ][cluster.metadata         ] [logstashsearch103-master-01] [common-2015.04.30] deleting index
[2015-07-16 14:10:59,057][INFO ][cluster.metadata         ] [logstashsearch103-master-01] [common-2015.05.01] deleting index
[2015-07-16 14:11:05,813][INFO ][cluster.metadata         ] [logstashsearch103-master-01] [common-2015.05.02] deleting index
[2015-07-16 14:11:06,932][INFO ][cluster.metadata         ] [logstashsearch103-master-01] [common-2015.05.03] deleting index
[2015-07-16 14:11:07,898][INFO ][cluster.metadata         ] [logstashsearch103-master-01] [common-2015.05.04] deleting index
[2015-07-16 14:11:19,269][DEBUG][action.admin.indices.delete] [logstashsearch103-master-01] [common-2015.05.05] failed to delete index
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (delete-index [common-2015.05.05]) within 30s
        at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:278)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-07-16 14:11:19,272][DEBUG][action.admin.indices.delete] [logstashsearch103-master-01] [common-2015.05.09] failed to delete index
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (delete-index [common-2015.05.09]) within 30s
        at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:278)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

So, --timeout extends the timeout for the *client* side, but the *server* side is unaffected.  You get a success message on the client side, presumably because you get a response from the server within the specified timeframe, but sadly the response is a timeout message.  It's likely, of course, that *some* of the indices you requested to be deleted were actually deleted, but probably not all of them.

Fortunately, I think there should be a trivial solution here: you can extend the server-side timeout for these operations with the `master_timeout=(value)` GET string argument.  If this were set and inherited the value passed from --timeout, I believe this would resolve this issue.

**Comment by untergeek** [comment]
I've just released v3.2.3 which adds `master_timeout` to the delete command only.  It will match the `--timeout` value, but only up to 300 seconds.  Hopefully this addresses the issue here.

I'm still concerned to see whether 300 seconds will be sufficient for some of these cases.  If that happens, my advice will be to try to delete in smaller batches.

**Comment by untergeek** [comment]
I need an "edge_case" label :smiley: 

While this is _technically_ a bug, it's also been fairly rare.

**Comment by dellis23** [comment]
For what it's worth, I ran into it also :-)  Thanks for the fix!

**Comment by TinLe** [comment]
Confirmed that latest v3.2.3 works with the large clusters I have.   Just deleted a month's worth of indices.
