### ISSUE TITLE
S3 snapshots do not work with S3 VPC endpoint

### ISSUE THREAD

**Issue by joerayme** [elastic/curator#421]
We've been using curator successfully to snapshot our Elasticsearch cluster for a while.

Recently, we created a [VPC endpoint](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html) for S3 and suddenly the snapshots stopped working. If you delete the VPC endpoint, it starts working again. The error we were getting is:

    2015-06-26 10:41:56,035 ERROR     Failed to verify all nodes have repository access.

The command we're using to snapshot is:

    curator --master-only snapshot --repository <repository> indices --all-indices

**Comment by untergeek** [comment]
In order to prevent snapshots from being incomplete (i.e. one of the nodes isn't able to write to the shared filesystem), Curator runs a [repository verification](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_repository_verification) before each run if you have a supported version of Elasticsearch (1.4+).

What this suggests is that adding the VPC endpoint has altered Elasticsearch's ability to write and/or verify snapshots, or it's too slow to respond, resulting in a false positive (or negative, as the case may be).  With the VPC enabled, you should probably run the API call manually and see what shakes out, both in the returned message, and in the Elasticsearch log files:

    curl -XPOST localhost:9200/_snapshot/REPOSITORY_NAME/_verify?pretty

Because this is a safety feature, I do not recommend trying to work around it without knowing for sure that all of your nodes are truly backing up properly.  That said, if this VPC endpoint is timing out, you can use the [`--skip-repo-validation`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/skip-repo-validation.html) flag, if you're using 3.2.0

**Comment by untergeek** [comment]
I'm closing this as there has been no further comment.  If you believe this is in error, please feel free to reopen the issue, or open another new one.

**Comment by joerayme** [comment]
Sorry for the delay in replying. We think it was just coincidence that we saw failures when enabling the VPC endpoint – we cleaned up our S3 bucket and it's all going fine now. Thanks for your help.

**Comment by untergeek** [comment]
:+1:
