### ISSUE TITLE
curator.optimize_index never returned

### ISSUE THREAD

**Issue by garyelephant** [elastic/curator#445]
The following code never returned sometimes and I don't know why?
```
import curator
from elasticsearch import Elasticsearch
client = Elasticsearch( hosts='es_in_production' )
ret = curator.optimize_index( client, 'downstream_success-2015.07.29', 3 )
```

**Comment by untergeek** [comment]
That's an excellent question.  Without enabling a logging instance, you won't be able to troubleshoot this very well.

I can tell you that if you don't increase the timeout in your client definition, it will likely return with either a failure, or keep running in the background, but with the client timed out (I've learned not to trust the `request_timeout` flag).  This is because an optimize is a very long-running operation, longer than the default 30 second timeout that comes with a client.

**Comment by garyelephant** [comment]
My Indices optimization typically take `< 20 minutes`, so should I make client `socket_timeout = 20 * 60` and leave `request_timeout` in optimize() default ?

```
client = Elasticsearch( hosts='es_in_production', socket_timeout=20 * 60 )
```

**Comment by untergeek** [comment]
The flag is just `timeout`:




```

client = Elasticsearch( hosts='es_in_production', timeout=20 * 60 )


```




I suppose the 20 * 60 works, but I'd still just put 1200. 



—Aaron

**Comment by untergeek** [comment]
The flag is just `timeout`:

```
client = Elasticsearch( hosts='es_in_production', timeout=20 * 60 )
```

I suppose the 20 * 60 works, but I'd still just put 1200.

**Comment by untergeek** [comment]
Since you haven't raised any new issues, I'm presuming this resolved things for you.

If you find another bug or issue, please open another ticket.
