### ISSUE TITLE
For curator sized-based index repository deletion, can we have one option to limit disk size for single index?

### ISSUE THREAD

**Issue by shanling2004** [elastic/curator#456]
I mean for scenario we want to make sure each single index disk size should be less than 200GB, 
shall we have new option "disk-space-per-index" for disk size limitation?
<code> curator delete --disk-space-per-index 250 indices logstash-* </code>

However, current disk_space option aims to control total disk size consumption for indices which satisfied with index selection criteria.

https://github.com/elastic/curator/blob/master/curator/api/filter.py#355

```
       for index_name, index_size in sorted_indices:
            disk_usage += index_size
            if disk_usage > disk_limit:
                delete_list.append(index_name)
```

**Comment by untergeek** [comment]
If you'd like to write this in, and add tests for it, I'd be happy to merge it.

**Comment by untergeek** [comment]
The more I look at this the stranger it feels.  Maybe I'm not understanding you correctly.

You want to ensure that a _single_ index does not consume more than 200GB?  What happens if it gets bigger than 200GB?  You're just going to _delete_ an index if it's too big?  Is that what you're requesting?

**Comment by untergeek** [comment]
Closing this for non-response.  I have other ideas for index rollover at size threshold, so that base will eventually be covered.
