### ISSUE TITLE
Don't use --timestring when command is snapshot

### ISSUE THREAD

**Issue by abo-adapt** [elastic/curator#466]
Currently snapshot cronjobs get --timestring added. This results in curator giving a warning that --timestring is used, but neither --newer-than nor --older-than is used. This prevents the command from actually executing through cron. This simple patch fixes that:

--- a/modules/curator/manifests/job.pp
+++ b/modules/curator/manifests/job.pp
@@ -81,7 +81,11 @@ define curator::job (
     $_regex = undef
   }

-  $_timestring = "--timestring '${timestring}'"
+  if ($command == "snapshot") {
+    $_timestring = undef
+  else {
+    $_timestring = "--timestring '${timestring}'"
+  }

**Comment by abo-adapt** [comment]
Minor syntax error in previous patch. Use this instead: 


--- a/modules/curator/manifests/job.pp
+++ b/modules/curator/manifests/job.pp
@@ -81,7 +81,11 @@ define curator::job (
$_regex = undef
}

 + $_timestring = "--timestring '${timestring}'"
 + if ($command == "snapshot") {
 + $_timestring = undef
 + } else {
 + $_timestring = "--timestring '${timestring}'"
 + }

**Comment by untergeek** [comment]
First, the patches you're submitting seem like they should be at the https://github.com/evenup-curator repo, for the [job.pp](https://github.com/evenup/evenup-curator/blob/master/manifests/job.pp) file, rather than for Curator proper.

Second, I'm not sure which version you're using, but it should run just fine. The warning is just that, plus a 10 second delay before continuing as normal.  Why would that prevent cron from running the command?  I understand that this may add lines to stdout, but that shouldn't prevent cron from functioning.

The Python code in question is [here](https://github.com/elastic/curator/blob/master/curator/cli/index_selection.py#L116-L122):

```
        if timestring and not newer_than and not older_than \
          and not (ctx.parent.info_name == 'show') \
          and not ctx.parent.parent.params['dry_run']:
            click.echo(click.style('You are using --timestring without --older-than or --newer-than.', fg='yellow', bold=True))
            click.echo('This could result in actions being performed on all indices matching {0}'.format(timestring))
            click.echo(click.style('Press CTRL-C to exit Curator before the timer expires:', fg='red', bold=True))
            countdown(10)
```

It would be extremely trivial to add another line: 

```
and not (ctx.parent.info_name == 'snapshot')
``` 
to this conditional, but I see no reason to do so until it can be proven _why_ it won't work in cron as-is.

**Comment by abo-adapt** [comment]
You are absolutely right. I meant to report this issue to evenup-curator, not directly to the curator project.
As to it just being a 10 second delay with the warning, I agree that it shouldn't prevent cron from running it, but at least on our servers, it did not run until I removed --timestring from the cronjob. Could it be because there is no interactive tty when cron is running it?

**Comment by untergeek** [comment]
It is possible, but that may depend on the platform.  In some cases, it may work if you put curator in a wrapper script, but not if you call it directly.  I'm not sure, but would love for more details.

In any case, #428 will likely fix this, when I get around to adding it.
