### ISSUE TITLE
Add index type filter to show and delete indices command

### ISSUE THREAD

**Issue by mcuelenaere** [elastic/curator#481]
I have a usecase where I need to delete a specific type of some indices instead of all the data.

This can be done by using the [delete_mapping](https://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch.client.IndicesClient.delete_mapping) method.

IIUC, `curator.api.delete_indices` and `curator.api.delete` need to be extended with a `types` argument and `curator.cli.index_selection.indices` needs to have a new `@click.option` decorator.

If this is an OK way to implement, I can create a PR.

**Comment by untergeek** [comment]
Curator is intended for index-level actions only. You're welcome to use the Curator API (http://curator.readthedocs.org) to accomplish this, or even maintain your own fork, but that functionality will not be merged into Curator.

Another part of the reason is that Elasticsearch 2.0+ will have changes regarding the use of "types."

**Comment by mcuelenaere** [comment]
Ok, then I'll create a script to perform this task.
