### ISSUE TITLE
Add support for client certificates 

### ISSUE THREAD

**Issue by skearns64** [elastic/curator#520]
It would be great if Curator allowed specifying a client certificate for PKI/x509 support when communicating to a protected Elasticsearch cluster. 

The ES Python client already supports this, I believe: 

http://elasticsearch-py.readthedocs.org/en/master/transports.html#elasticsearch.connection.Urllib3HttpConnection

**Comment by richm** [comment]
+1

**Comment by msimos** [comment]
In `def get_client(**kwargs):` if you add `kwargs['client_cert'] = "/path/to/cert.pem"` then you can add in certificate based authentication. It seems fairly easy to add another parameter to add this in.

**Comment by richm** [comment]
@msimos I don't understand.  Isn't that what the proposed commit does?

**Comment by msimos** [comment]
@richm sorry i didn't see that, thats great

**Comment by idsvandermolen** [comment]
This also increased required version for elastichsearch-py from 1.8.0 to 2.3.0 which might not be documented anywhere. So it also won't work with elasticsearch 1.x anymore.

**Comment by untergeek** [comment]
@idsvandermolen It passes tests with elasticsearch 1.x (see the build results link on the repository home page), though there are some exceptions that don't get caught properly for 1.x.  But it is still functional.

This will be the last release branch to be reverse compatible with ES 1.x.  There will not be a 3.6.0 release.  4.0 is coming soon.

**Comment by idsvandermolen** [comment]
ok, but I think I'm confused with the different major numbers. I thought elasticsearch-py 1.x was still required for ES 1.x and that elasticsearch-py 2.x didn't work for ES 2.x .

**Comment by untergeek** [comment]
@idsvandermolen The version lockout is really not as complete as it might seem.  There are features in the es-py 2.x branch that won't work against a 1.x elasticsearch cluster, of course.  But so much of the underlying API is still _identical_ that for the feature set that Curator uses, I can still use es-py 2.x with 1.x elasticsearch clusters.  Until the most recent version, you could still get away with using es-py 1.8 with Curator.  In order to make use of the PKI structure, though, es-py 2.3.0 is required.  As I pointed out, the tests with Curator all pass in 1.x clusters, even with es-py 2.3.0.

**Comment by idsvandermolen** [comment]
@untergeek Thanks for your explanation, this is clear now.
