### ISSUE TITLE
Publish releases to Docker Hub

### ISSUE THREAD

**Issue by xaka** [elastic/curator#528]
Would be nice to have it as official Docker Hub repository in same way as it's done for https://hub.docker.com/_/elasticsearch/. You already have Dockerfile in place so it's matter of automation I guess. Thanks!

**Comment by svenmueller** [comment]
+1

**Comment by jakommo** [comment]
Not a real answer but please note https://hub.docker.com/_/elasticsearch/ is not developed or provided by Elastic. It's just an "official" docker library image.

**Comment by untergeek** [comment]
When Elastic releases "official," Elastic-provided docker images, then we might release this.  Until then, it's on-hold.

**Comment by czerasz** [comment]
Published an [image](https://hub.docker.com/r/czerasz/docker-elasticsearch-curator/) with curator `4.0.1` if someone needs it.

Already tested it and it works nice :-)

**Comment by davidkarlsen** [comment]
@untergeek it's about time now - since elastic publishes official images of kibana and elastic. Also the one in the library is currently lacking support for 5.1.1.

**Comment by untergeek** [comment]
For anyone else looking here, until further notice, I would recommend using https://hub.docker.com/r/bobrik/curator/

**Comment by praseodym** [comment]
I've also created an automated Curator Docker image build based on the official [Python 3-alpine](https://hub.docker.com/_/python/) image.

It is available from both Docker Hub and Quay:
* https://hub.docker.com/r/praseodym/elasticsearch-curator/tags/
* https://quay.io/repository/praseodym/elasticsearch-curator?tab=tags

**Comment by davidkarlsen** [comment]
Great - it would be even more grate if elastic inc would curate this image along the rest of ELK

**Comment by geekofalltrades** [comment]
@untergeek , any motion on this? I'm about to start deploying ELK stacks in Kubernetes, and I'd love to see curator up alongside the others on docker.elastic.co.

**Comment by frittentheke** [comment]
@untergeek Since your already have a Dockerfile yourself, wouldn't it make sense to have a somewhat offical image published somewhere? Otherwise everyone and their cat is simply forking your code at some point to create their own images with likely no real maintenance or updates.

**Comment by MaikJaek** [comment]
@untergeek 
Hi Aaron, 

do you have any news regarding the suggested idea of publishing images on docker.elastic.co ? We'd love to use an official image for curator, as well.

**Comment by pete-woods** [comment]
Given you now public official Docker images to https://www.docker.elastic.co/, is it the right time to start publishing this, too?

**Comment by untergeek** [comment]
Sorry everyone, for the prolonged delay in response. Yes, I would like to offer an official Elastic Curator image. Not sure yet when this will happen. It probably won’t be until the next major version is released. And I’m not sure when that will be. 

At the end of the day, Curator is still a one-man show (me), and I am a consultant now, rather than a full-time developer, so my development time is more limited. Coming soon will be Index Lifecycle Management, which will cover the most common Curator use cases, complete with a UI in Kibana. For anything requiring more complicated flows, Curator will continue to be the go-to tool for index management. As such, yes, an official Docker image is an important step. I will get to it when I can, as it involves me working with the infra team that does image publishing, etc. I will get to it when I can, but it will not be the next few weeks, what with the holidays coming.

**Comment by pete-woods** [comment]
It's about a 5 minute job to set up an automated Docker Hub image, in case you haven't done it before. I'd be happy to take it from there instead.

**Comment by frittentheke** [comment]
@untergeek please also accept my offer to assist with setting things up. This really only takes a few minutes when using Travis CI ... https://ops.tips/blog/travis-ci-push-docker-image/

**Comment by untergeek** [comment]
I appreciate the offer, @frittentheke. However, if it were as simple as that, I would already have done it. There are internal and external politics and multiple systems involved. Our infra team manages the docker hub images. I have to go through them. Curator is not deployed or managed on those Jenkins servers, which manage the automated building process. I have to go through a process to get things on their servers if I want this to happen. It's not high enough on the priority list to escalate and get Curator both on the internal build system and in Docker Hub in an expedited time frame—especially not since Index Lifecycle Management is almost ready for release.

**Comment by pete-woods** [comment]
You don't even need Jenkins, TravisCI, etc if you use Docker Hub, it has its own builders. At the minute I'm having to use a GitHub mirror of your repo to set up automated builds to here.

https://hub.docker.com/r/surevinecom/elastic-curator/

**Comment by untergeek** [comment]
You’re right, but that’s not the point. My Infra team manages all docker building and publishing. I can’t be a one-off.

**Comment by frittentheke** [comment]
@untergeek especially with all your great new releases and the recommended image from bobrik not running automated builds / pushes to DockerHub (https://hub.docker.com/r/bobrik/curator/tags) this would be awesome to have.

**Comment by eyalzek** [comment]
An official image for 5.7 would be greatly appreciated :)

**Comment by untergeek** [comment]
I may never push (or be able to push) Docker builds of Curator to the `docker.elastic.co` repository, but I will start publishing builds of the Dockerfile in GitHub to `untergeek/curator:major.minor.patch`.

Starting with [version 5.7.6](https://cloud.docker.com/u/untergeek/repository/docker/untergeek/curator), this is now available:

```
docker pull untergeek/curator:5.7.6
```

Please note this is the `curator` binary, and not `curator_cli`.

**Comment by guessi** [comment]
@untergeek good to know there's an update from the author :tada: 

But still looking forward for image build & push automation being integrated. Test automation have being integrated into [.travis.yaml](https://github.com/elastic/curator/blob/master/Dockerfile), adding a new step for image build automation shouldn't be a problem.

The only concern would be which shared account would be used for build automation, privileged user(s) could have change to retrieve the secrets, or leak via a bad pull-request, is that the reason for not having that docker image build automation?

btw, you might want to fix the repo link in the comment [above](https://github.com/elastic/curator/issues/528#issuecomment-490132387),
- From: https://cloud.docker.com/u/untergeek/repository/docker/untergeek/curator (5xx error)
- To: https://cloud.docker.com/repository/docker/untergeek/curator
```

**Comment by untergeek** [comment]
I will not be automating anything in the foreseeable future. I just don't care enough. I will happily publish releases to Docker Hub at the same time I add RPM/DEB packages, Windows MSI/ZIP, and the PyPI releases.

**Comment by koshatul** [comment]
Sorry to resurrect an old issue, but I made an automated build of the curator repo into docker hub using Github Actions (so I don't have to maintain it and keep updating for new versions).

https://hub.docker.com/r/koshatul/curator/tags

Is it OK to leave it going ?

**Comment by pataquets** [comment]
Great to know it. Thanks for sharing, @koshatul.

Since it looks like that @untergeek images' on Docker Hub are published somewhat manually, I would suggest you submitting a PR to enable all that magic to happen from this repo, so it reliefs Aaron by making it set-it-and-forget-it to get them published automatically in his Hub account (if Aaron is OK with that). Judging by comments and reactions on the issue, you'll get tons of good karma :grin:.

**Comment by koshatul** [comment]
GitHub Actions actually disables scheduled runs after a period of inactivity for the repository, doing it for this repo itself would mean just triggering on tags/releases which would be _much_ more efficient.

[koshatul/docker-curator/.github/workflows/ci.yml](https://github.com/koshatul/docker-curator/blob/master/.github/workflows/ci.yml) ran until 8 months ago.

It'd be hard to do a PR for unless I knew where it would be published, like will it end up as `docker.elastic.co/curator/curator:tag` or `elastic/curator:tag` (on registry.docker.io) or would docker adopt it and it would get a top-level name of `curator:tag` 🤷🏻 .

**Comment by untergeek** [comment]
These are currently published at Docker Hub at `untergeek/curator:TAG`

See: https://hub.docker.com/repository/docker/untergeek/curator/general
