### ISSUE TITLE
Create filtered alias with curator

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/curator#553]
WE should consider adding a new parameter to set a filter in a/multiple aliases.

**Comment by gmoskovicz** [comment]
@untergeek what do you think about this?

**Comment by untergeek** [comment]
I'm a little worried about feature creep.  While I understand the utility, how do you define this on a command-line?  This is the kind of feature that requires a config file, rather than command-line options.  Also, what is the reasoning to add a filter after the fact, instead of using an index template to add it at index creation time?  There's a need to add a filter after the fact?

I'd like input from the product team on this.  I'm not sure if Tanya, Steve, or Alvin is the right person.

**Comment by untergeek** [comment]
Fixed by #614
