### ISSUE TITLE
Signing requests to AWS ES

### ISSUE THREAD

**Issue by alexandrz** [elastic/curator#566]
Is it possible to sign requests with AWS credentials?

**Comment by untergeek** [comment]
@alexandrz A good question.  The project that actually matters is https://github.com/elastic/elasticsearch-py, as that's what Curator uses.  Also, elasticsearch-py uses the urllib3 module, so it becomes a question of how that would be handled up the chain.  If elasticsearch-py and urllib3 can do it, then it would be possible to build support for this into Curator.  I've sent a private message to the maintainer of elasticsearch-py regarding this.

**Comment by untergeek** [comment]
@alexandrz Would this do it? http://elasticsearch-py.readthedocs.org/en/master/#running-with-aws-elasticsearch-service

**Comment by alexandrz** [comment]
Thank you! Yes, this would do it! Is it now possible to configure curator to use it?

**Comment by untergeek** [comment]
I would need you to add/test the functionality, pretty much exactly as described there.  If you cannot easily do that, I can try to create a branch with it, and roughly add the args to the command-line and let you test that.

**Comment by alexandrz** [comment]
@untergeek I can not easily do that, since I don't know python, but I would test it for sure.

**Comment by servomac** [comment]
I have been working a little on this issue and I have a first usable version. I will write some tests, refactor a little bit the code and make a pull request (now there are some tests that aren't working).

https://github.com/servomac/curator/tree/aws

**Comment by untergeek** [comment]
You may need to hold off a bit on a pull request as I will not be merging any new features into the Curator 3.x branch. 

I'm in the middle of release-prep for Curator 4.0, which is a near-complete rewrite.  Most of your changes to `get_client()` should still transfer over as I've largely kept that method intact, so that's a good thing.  The rewrite uses configuration files instead of an ever-growing number of command-line arguments, so that should also make your additions simpler there.  

Please continue to use and test your forked version against ES in AWS, though.  This will be important usability testing.

We'll have to be careful about how we name and refer to this functionality.  AWS ES, at least in my mind, refers to Amazon's Elasticsearch offering, rather than Elasticsearch deployed to AWS instances.  Curator 4.0 will not be reverse compatible with Elasticsearch versions less than 2.0, and therefore will be wholly incompatible with the Amazon Elasticsearch offering, which is presently stuck at Elasticsearch v1.6.

**Comment by untergeek** [comment]
This should be addressed by #595 and #596 with Curator 4.0 imminent.

If you feel this is in error, please feel free to reopen this ticket or open another.
