### ISSUE TITLE
Snapshot did not complete successfully but the snapshot file was created

### ISSUE THREAD

**Issue by catalincatana** [elastic/curator#576]
If there are 2 snapshots done in the same time, Elasticsearch will throw an error saying that there is already a snapshot process running - which is expected - and Curator says: 

Client raised a TransportError.
Job did not complete successfully

but when i looked into the backup folder, the snapshot file was there.

I tried to catch the curator Exit code and retry the snapshot after 5 seconds and instead having only 1 snapshot..i had 2. (First try that was failed, and the second try that succeeded)

Is this a bug or am i doing something wrong?

Thank you for your time!

**Comment by untergeek** [comment]
@catalincatana I'm not sure what happened on the Elasticsearch side that resulted in both a failed (empty) snapshot and a successful one.  It may be that this is expected behavior.  I've never actually looked at the files after a failed snapshot attempt.  I use the API to check and see what's there.  Chances are good that if you check the API, or use `curator show snapshots --all-snapshots --repository REPONAME` that you'll only see the valid snapshot.  If Elasticsearch is doing attempting to create a snapshot, then abandoning the empty file/directory, that may be a bug.  Without knowing more about your environment, cluster, version(s), repository type, etc, I can only guess what happened.  Remember, Curator only makes API calls, and responds to the response codes it receives.  Everything else is at the Elasticsearch level.

**Comment by catalincatana** [comment]
Thank you for your fast response! 

I have looked through the logs of elasticsearch and it seems it tries several times(4) to take the snapshot but without success. Despite this fact, the snapshot file is created and is not empty. So if i try twice to take the snapshot..both will be valid files. 

Should i address this issue to elasticsearch team? I have put it here because curator says job not completed successfully but the snapshot is created (and valid). 

Thank you!

**Comment by untergeek** [comment]
@catalincatana what is the full command-line (minus any connection credentials) you're using with Curator?  What version of Elasticsearch are you using?

**Comment by untergeek** [comment]
@catalincatana Also, after taking the snapshot, do you see both the complete and incomplete snapshots in the `show snapshots` command?

**Comment by catalincatana** [comment]
The command used is something like this:

**Comment by untergeek** [comment]
> Elasticsearch version is: 1.1.1

That may be some of the issue.  Elasticsearch is on version 2.2.0 right now, with 1.1.1 being a year or so old.  Snapshots were only added in 1.0.0, and many bugs and issues have been squashed since then.  

Versions less than 1.4 are deprecated and no longer supported, so I highly recommend upgrading—carefully and methodically—to more recent versions in stages.  The reason for this is that your 1.1.1 indices may not be recognized in a direct upgrade to 2.2.0.  You may have to go from 1.1.1 to 1.4.4, to 1.7.3, to 2.2.0, or something like that.  You may also have to run an optimize (don't forceMerge to 1 on the first time, unless they're already optimized) in between to get _new_ segments created which will be recognized in newer versions of Elasticsearch.

I'm not 100% sure of your upgrade path, but you can certainly find out by asking at https://discuss.elastic.co/c/elasticsearch

**Comment by catalincatana** [comment]
I will try to do that and see if i encounter any other issues. 

Thank you very much for your time and responses. You are doing a great job!
