### ISSUE TITLE
Delete up to #

### ISSUE THREAD

**Issue by gfrankliu** [elastic/curator#593]
When I use curator to clean up daily indices older than 30 days, since there are hundreds of indices per day, ES deletes first few and then starts timing out all the rest. Is it possible to run curator with a limit, say only deleting up to 10 indices older than 30 days? I can then run curator multiple times during a day to even out the load to ES.

**Comment by untergeek** [comment]
You're really creating and deleting hundreds of indices per day?  How many active indices do you retain on an ongoing basis (per node, the whole cluster)? Each shard, each index has a management cost to the cluster.  If you are creating hundreds of indices per day, and then deleting hundreds of "expired" indices per day, this is a tremendous overhead for an Elasticsearch cluster.  

It may be possible to do what you're requesting, but I'm not sure retooling Curator is the proper solution to this issue.  If you must use a heavy index/shard count per day, you may be better served with a custom script using the Curator API that retries indefinitely until all deletes are completed.  Curator retries 3 times because that's all it should take.  Even that concession was debated hotly at the time it was requested.

Curator is just a specialized API frontend.   Curator sends API requests to Elasticsearch, and Elasticsearch responds.  So why does Curator time out for your use case?  Because Elasticsearch rebalances the cluster by shard count per node by default.  If you're trying to delete so many at once, Elasticsearch is trying to rebalance the cluster.  So many shards and indices shuffling around is taxing your cluster quite heavily, and it is unable to simultaneously rebalance _and_ process new delete (or even create requests, I'd wager) in a timely manner.  The timeouts are an indication of a _very_ busy cluster, as described, and Curator is only responding with what it received from Elasticsearch.

**Comment by untergeek** [comment]
Closing in favor of #649, which will add filter by count.
