### ISSUE TITLE
Add information on how to use the example files

### ISSUE THREAD

**Issue by Gueust** [elastic/curator#610]
It seems that the example files are some yaml representation of cli commands.

However, I haven't found any documentation on how to use them. Maybe a simple README in the example directory, with the few lines explaining how to use them could be sufficient. I haven't found any tag/command in the cli tool allowing to take a yaml file instead of the command line.

I'm sure it is very simple, but I can't find it.

**Comment by untergeek** [comment]
https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/index.html

Specifically: 

* https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/actionfile.html
* https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/configfile.html
* https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/examples.html (There was an asciidoc bug here that should be fixed in about 10 minutes or so.  Some of the examples are under a different trunk, titled "create_index")

**Comment by untergeek** [comment]
Sorry for the confusion, but the links to the usage documentation are in the main README for the project.

**Comment by untergeek** [comment]
@Gueust are you trying to use Curator 4.0?  If not, be sure to look at the 3.5 documentation on the above site links.  There's a drop-down to select the proper version.

**Comment by Gueust** [comment]
I see, the default documentation (i.e. the links in the README on the master branch) is indeed 3.5 while the examples files are 4.0 features. So one should look at the 4.0 documentation !

Thank you so much, and sorry for not being able to find it myself. This possibility to use configuration file seems very cool :) I think we can close the issue (maybe we can remedy my error by not pushing the example into the master branch, keeping them only in the 4.0 branch. Just an idea).

**Comment by untergeek** [comment]
Master is 4.x now, so this is not incongruous.  The 3.x branch has its own documentation.  When 4.0 is officially released, it will be "current," so the URLs will work then.  I didn't want to change the README to point to the 4.0 tree.
