### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by michaelseto** [elastic/curator#621]
Hello All,

I've got Curator installed, now I am attempting to run the following ::

sudo python /usr/lib/python2.7/site-packages/curator/curator.py --host localhost -d 30

I get the below error, and I am not sure why ::

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 2, in <module>
    from .cli import cli
ValueError: Attempted relative import in non-package

I am relatively new to Python, so of course I am lost by this error which appears cryptic to a new person.

**Comment by michaelseto** [comment]
Also, if I try this ::

[root@selk01 curator]# python -m curator
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/curator/curator.py", line 2, in <module>
    from .cli import cli
ValueError: Attempted relative import in non-package

**Comment by untergeek** [comment]
Which version of Curator did you install?  The command line you're attempting to use is from Curator 1.x., but `from .cli import cli` indicates a much more recent version.

Also, how did you install Curator?  You're attempting to launch `curator.py`, which is not how it's supposed to be run.  Curator installs an `entry_point` at `/usr/local/bin/curator` or on some systems, `/usr/bin/curator`.  You will always see the `relative import` message if you try to execute `curator.py` from the module path, rather than using the endpoint.

You should try just running: `curator --help` from the command line and see what you get.

**Comment by michaelseto** [comment]
Hello,

[root@selk01 curator]# curator --version
curator, version 3.5.1

How I installed ::

pip install elasticsearch-curator

After I installed, I tried ::

[root@selk01 curator]# curator --host localhost -d 30
Error: no such option: -d

**Comment by untergeek** [comment]
As mentioned, you must be reading a _very_ outdated set of instructions for Curator.  The command-line flags are very different from whatever you've been reading.  Have a look at the output of `curator --help` to see what I mean.

There is a link to the Curator documentation in the output of `curator --help`, but I'll include it here as well: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/index.html

**Comment by untergeek** [comment]
Closing since this is a non-issue.

**Comment by reqless** [comment]
I got it to work using the current command line flags. Yay! I do have one last question - is this automated? I just deleted indices older than 30 days, but not sure if that was a one time thing or.....does this need to be a cronjob?

**Comment by untergeek** [comment]
It does need to be a cron job.

**Comment by reqless** [comment]
Ok thank you!
