### ISSUE TITLE
Add recovery prioritization functionality

### ISSUE THREAD

**Issue by markwalkom** [elastic/curator#629]
Given ES can [do this](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/recovery-prioritization.html), it'd be nice if Curator could apply a shifting priority, where newer indices have that higher priority.

**Comment by untergeek** [comment]
Curator 4's configuration doesn't mesh with this, but I intend to put some of the v3-style command-line features back in as separate scripts.  Perhaps this is one that would make sense to have in that bucket.

**Comment by danielmotaleite** [comment]
Please add this! I have a big setup and just updated to 5.1.2... of course, ES choose to recover first OLD indexes instead of today. Manually set this is annoying and one automatic way would be great

Why not reuse the action `delete_indices` and add the action `priority_indices`, with the same filtering ? i would imagine that the commands aren't that different (but of course, i do not know curator code)

**Comment by danielmotaleite** [comment]
Also add support to change the refresh, it is similar to priority, just take one argument with the value and the filter. one example of the call:

```
PUT /syslog-*/_settings
{
    "settings": {
      "index": {
        "refresh_interval": "15s"
      }
  }
}

```
https://sematext.com/blog/2013/07/08/elasticsearch-refresh-interval-vs-indexing-performance/

If we could use curator to set a long refresh time to old indices, we could get better performance and higher elasticsearch cache hits

**Comment by untergeek** [comment]
@danielmotaleite Changing the `refresh_interval` only makes sense for indices actively indexing documents because refreshes _only_ happen when new documents are coming in.  For time-series indices, it makes sense to set this in the index template, rather than with an external tool.  Because of that, it is uncommon to need to change this setting on the fly.

See: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docs-refresh.html

> Elasticsearch automatically refreshes **_shards that have changed_** every `index.refresh_interval` which defaults to one second. 

_(Emphasis added)_

**Comment by danielmotaleite** [comment]
@untergeek  you are right! sorry! forget about the _refresh_interval_ ! 

_priority_indices_ is still important :)
How about using the same code layout for _delete_indices_ to update the _priority_indices_

**Comment by untergeek** [comment]
It's not quite as simple as that, unfortunately.  If you'd like to take a stab at adding that feature, I accept pull requests, and I'd be happy to help with tests and such.

**Comment by untergeek** [comment]
Since newer indices automatically have the higher priority (according to the documentation), this is desirable, but less pressing.

**Comment by untergeek** [comment]
Also going to lump this under #656
