### ISSUE TITLE
Delete snapshots regardless of repository

### ISSUE THREAD

**Issue by redserpent7** [elastic/curator#630]
Hi,

I am trying to utilize curator in an automatic backup solution for my cluster. The backup requirements are as follows:

-Do full backup once a week,
-Incremental backups daily
-Delete snapshots older than a 3 months

I do not have a problem creating a new repository every week and doing daily snapshots on it. My problem is that when I have to delete old snapshots, I need to specify a repository name. Is there a way to tell curator to delete from all repositories?

**Comment by untergeek** [comment]
The Elasticsearch API does not allow for this, so Curator does not either.  The only way to accomplish this would be to get all repositories, and iterate over them.  This _could_ be done using the Curator API, though it would be unwieldy.

I would invite you to consider re-thinking your backup strategy a bit.  Snapshots are not the same as other incremental backups.

Snapshots are incremental at the _segment_ level, not at the file or document level.  When a snapshot is taken, it backs up every _new_ segment it has no record of, and points to _every segment already snapshotted._ No segment is ever deleted as long as a single snapshot points to it. This means that every single snapshot is like a full snapshot, because it points to every segment necessary to restore the cluster to that point in time. You shouldn't need to have a new repository every week.  You could just do weekly snapshots and those would be your full "restore to that point in time" backups.  You could delete _any_ daily snapshots in between these weekly snapshots and that would cover things for you.  Just name them differently (you could prefix them with `daily-` and `weekly-`) so they are easily found and pruned by Curator.  You could then keep daily incremental snapshots as long as you deemed necessary, and weekly ones at a different retention.

**Comment by untergeek** [comment]
Going to close this as I do not believe it's a usage pattern that, as described, neither Elasticsearch nor Curator are intended to address.

If you feel this is in error, please feel free to re-open this issue, and elaborate on your reasoning.
