### ISSUE TITLE
Different exit values for different errors

### ISSUE THREAD

**Issue by ddmng** [elastic/curator#633]
I'm trying to include curator in a bash script to do maintenance on my time-based indices.
Since the executable always returns `1` both for connection failure and for errors on required indices, I can't decide what error to report and which action to apply (exit or create the index with a given time range).
It would be good I think if curator would return different exit values for different errors and 0 for no errors.

**Comment by untergeek** [comment]
I used to have different exit codes for different actions.  It was a huge headache, and I got a lot of flak for it, so I removed that feature.

Curator v4 is in alpha right now, and it's not really as command-line oriented as v3.  It uses YAML config files now.  You will need to read through logs to see what kinds of failures happened, as the object-oriented approach is just catching exceptions and exiting with a `1` on any failure, still.  I do not anticipate this changing for Curator v4, due to this change.  No other changes will be back-ported to Curator v3.
