### ISSUE TITLE
AWS ES snapshot support

### ISSUE THREAD

**Issue by yissachar** [elastic/curator#639]
When using Curator with AWS Elasticsearch I can't take snapshots. It fails because because the endpoint `/_snapshot/_status` is not exposed by AWS. 

I believe this could be worked around by using `/_snapshot/<repository>/_status` instead, as that endpoint is exposed by AWS.

I'm not familiar with the Curator internals, so I'm not sure if this is a viable fix or not, but on the surface it seems that `/_snapshot/<repository>/_status` should provide the info required for Curator to take a snapshot.

**Comment by yissachar** [comment]
The snapshot action checks for any running snapshots and fails if there are any: https://github.com/elastic/curator/blob/master/curator/actions.py#L716

It's not clear to me what the intent of this check is. If it's just to prevent accidentally running the same snapshot twice, then the fix I mentioned above should work.

**Comment by untergeek** [comment]
While I can, and will likely, make this change, the problem is that Curator 4 does not support versions of ES < 2.0.  That won't help you with AWS ES.  I don't know that I have a great desire to make changes to Curator 3.x at this point, either.

**Comment by untergeek** [comment]
And the check in the line you mention is because if you send a snapshot request to Elasticsearch, and a snapshot is already in progress, it will fail.  Rather than try to process the "why" of all possible fails, Curator first eliminates this potential fail.  This is disturbingly common with slower repositories, with people trying to do hourly snapshots, so the check is there to prevent that from causing issues.

**Comment by yissachar** [comment]
Ah, fair enough. I hadn't realized that bit about the versions. If this change doesn't make it into 3.x, I can perform the snapshots manually. Working with Curator is so much nicer though.

**Comment by untergeek** [comment]
Truthfully, I don't think I can safely remove this functionality, as I look at it.  While you correctly read that the check for `/_snapshot/_status` is to ensure no other snapshot is running, it's not limited to the current repository.  Elasticsearch might have multiple repositories configured, but only one snapshot can be run at any given time, to any of them.  That's why Curator checks for snapshots across _all_ possible repositories.  

While I _could_ theoretically test my way around this by just not testing for existing snapshots and try to catch failures with a `try/except` block, it's a monkey patch approach to a problem that doesn't exist anywhere outside of AWS ES.  As such, I'm not going to be fixing this.  I apologize for the inconvenience.

**Comment by yissachar** [comment]
Understood, thanks for looking into this.

**Comment by cjuroz** [comment]
@untergeek, as you may know AWS ES 5.3 has been released recently and they claim compatibility with Curator. I have been using Curator 5 API for index management through Lambda function.

So far, no problem with index cleaning BUT create snapshots is failing because AWS guys still didn't expose `/_snapshot/_status` endpoint. I am opening a bug through them (need to wait "few hours" to post for first time..., will update with url when they allow me to post). 

Just to let you know about this or if @yissachar suggestion or another workaround could be applied...

**Comment by untergeek** [comment]
Thanks for the update, @cjuroz. Please open a separate issue and I will update the docs accordingly.
