### ISSUE TITLE
Add a filter to select today/yesterday/week/month indice

### ISSUE THREAD

**Issue by ebuildy** [elastic/curator#651]
(not sure if it's the best place to post this) Would be good to make easier "today indice" selection. 

Rather than:

    curator alias --name today indices --newer-than 2 --time-unit days --timestring %Y.%m.%d

Could be:

    curator alias --name today indices --today --timestring %Y.%m.%d

Same thing for current week, month.

**Comment by untergeek** [comment]
@ebuildy It's an interesting idea, but I'm not sure if it's worth pursuing within the context of the newer Curator 4 configuration.  It would further complicate the YAML configuration to add "today|thisweek|thismonth" type configuration aliases, and then properly tokenize them.  Also, because Curator 4 converts all timestamps to epoch internally, I don't know that this is the best approach. "Today" is subjective, based on your timezone, and it could be very confusing for users, where epoch time is by definition, UTC only.

**Comment by untergeek** [comment]
I'm closing this for lack of comment, and that it doesn't make much sense in Curator 4.  If you feel like this is in error, feel free to reopen the ticket, or open a new one.
