### ISSUE TITLE
Add a "show aliases" feature, or an --is-alias option to index selection

### ISSUE THREAD

**Issue by ynux** [elastic/curator#680]
We have issues when an alias spans over open and closed indices. Because of this, I have to remove the indices from the alias before I close them. To do this, I need a list of all existing aliases. I do this with curl and the _cat/aliases API currently, but the rest of the script uses curator, so that would be more consistent.
The most general implementation would probably be to add an "--is-alias" option to the index selection.

**Comment by untergeek** [comment]
It seems you are still using Curator v3.x if you are looking for an `--is-alias` flag.  Curator is now at version 4.0.1 and has a new configuration syntax, and has an option that should do what you want: https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/close.html

Please see if the [`delete_aliases`] option covers your use case.

**Comment by untergeek** [comment]
@ynux do you have any feedback here?  I'm going to close this and consider it moot for the "close indices" use-case if I don't hear a response soon.

**Comment by ynux** [comment]
Thanks for your answer, and you are right, I'm still using curator 3. I installed curator 4 and will test the https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/option_delete_aliases.html option tomorrow. I think it is what I'm looking for, though I wouldn't call it "aliases will be deleted from indices" but "index will be removed from aliases".

**Comment by untergeek** [comment]
> I wouldn't call it "aliases will be deleted from indices" but "index will be removed from aliases".

While technically accurate, too many new users (and even old ones) do not understand the distinction.  I applaud you for understanding it so well.

However, it's important to note that it's also accurate this way as `aliases` is a key in the index metadata, with the aliases that the given key/index is associated with as the value.  In that light,  "deleting aliases from indices" still works, and since that's what it looks like after it's done, it's rather moot how it's described, so long as users know that the index and alias will be disassociated after the action.

I look forward to hearing whether the `delete_aliases` option works for your use case.

**Comment by ynux** [comment]
The `delete_aliases` option works perfectly for me. Thanks.
I'm also happy that we now moved to curator 4. The curator 3 command lines were getting difficult to handle. Putting the central configuration into a CONFIG.YML removes a lot of duplication.
A third praise: It's good that you consider the confusion of new users, and at the same time strive to keep the wording technically correct.
