### ISSUE TITLE
Upgrade to ES 2.3.3 appears to break curator

### ISSUE THREAD

**Issue by slmingol** [elastic/curator#683]
I recently installed ES 2.3.3 and am encountering this error on CentOS 6.8 w/ Python 2.6.

```
/usr/bin/curator --quiet --loglevel ERROR delete indices --prefix qa --time-unit days --older-than 1 --timestring '%Y.%m.%d'
Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch>=2.3.0,<5.1.0
```

**Comment by untergeek** [comment]
How did you install Curator?  Via `pip`?  By package?  Because the error here is talking about a python problem, not an Elasticsearch problem.  I know it _looks_ like an Elasticsearch problem, but that `elasticsearch>=2.3.0,<5.1.0` is actually referring to the elasticsearch python module, not your version of Elasticsearch.

The fix is well described in the FAQ for Curator: https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/entrypoint-fix.html

You need to upgrade `setuptools` for Python to fix this, then it will start working again.

**Comment by jpsandiego** [comment]
Which version of curator are you running with?

Is that command line syntax valid with the current versions (v4) of curator? I think everything has moved to YAML.

**Comment by slmingol** [comment]
I'm using 4.0.1.

**Comment by untergeek** [comment]
That command-line syntax will _not_ work with 4.  You will need to read up on the 4.0 docs: https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/index.html

And you will still need to upgrade `setuptools` for your Python before it will work.  The instructions for that are at https://www.elastic.co/guide/en/elasticsearch/client/curator/current/entrypoint-fix.html

**Comment by slmingol** [comment]
OK, thanks @untergeek - I'll go do my homework and read up on that, sorry I bothered everyone, I didn't realize there was a significant change to the switches. My bad!
