### ISSUE TITLE
Add .watches to kibana filter

### ISSUE THREAD

**Issue by ynux** [elastic/curator#692]
Presently, the kibana filtertype removes "indices .kibana, .marvel-kibana, kibana-int, and .marvel-es-data from the list of indices", according to https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_kibana.html . For people using Watcher, I think they'd be sad if their .watches index was accidentially gone / they'd be grateful if this filter saved it.

**Comment by untergeek** [comment]
I appreciate the suggestion, but to me it makes no sense to add a _Watch_ index to a _Kibana_-specific filter.  In any case, preventing any index starting in `.watch` from being acted on is as simple as adding another filter block:

```
- filtertype: pattern
 kind: prefix
 value: .watch
 exclude: True
```

It wouldn't be too hard to add another filtertype for watches, but that seems a lot of work to replicate the above functionality for a _single_ index, or index pattern. The Kibana filtertype exists because it existed in previous versions (and as such, it would be expected), and there are multiple, dissimilar indices which are used by Kibana/Marvel, so this prevents the user from having to add multiple filter blocks to catch all of those.

**Comment by ynux** [comment]
Yes, well, I admit that I was thinking more of a "protect elasticsearch internal indices"-filter. OK then, let people add the filter block, thanks for providing it. It was nice of Curator 3 to protect .kibana.

**Comment by ynux** [comment]
One small remark: The above filter block would also exclude the `.watch_history-YYYY.MM.DD` indices, which you may actually want to close and delete, so we're using `value: .watches`
