### ISSUE TITLE
Allow use of date params in alias keys

### ISSUE THREAD

**Issue by matthughes** [elastic/curator#709]
I'd like to be able to have the following create_index action:

```
name: foo-%Y-%m-%d
extra_settings:
  aliases:
    foo-v1-%Y-%m-%d: {}
    foo-v2-%Y-%m-%d: {}
```

Curator supports strftime patterns in the name field, but not the aliases section.

**Comment by untergeek** [comment]
This will be coupled with parallel work for #511

**Comment by untergeek** [comment]
#511 will not be performed because Elasticsearch date math is sufficient. Adding strftime for aliases will be possible, but it will not support future index names.  Does that present an obstacle?

**Comment by untergeek** [comment]
Actually, there's nothing I can do here at all.  I finally read the fine print.

You called this ticket, "allow use of date params in alias keys", but what you're asking for is for Curator to parse the `extra_settings`, which can be arbitrary.  Curator does not parse the `extra_settings` because it can't predict with any reliability what will be there.  It's just not a feasible feature request.

If you know what you're up against, you can always use environment variables and pass those to Curator.
