### ISSUE TITLE
Epoch option for age filter

### ISSUE THREAD

**Issue by jbwl** [elastic/curator#731]
I'd like to request a feature:

I think the current setting of an epoch in the age filter (as a point of reference) is not very practicable. An automated task would have to read / update / write the yaml settings file if it tried to change the epoch.

My use case is that I that the epoch for my age filter needs to be changed frequently, i.e. "snapshot all indexes prior to date x". That date is calculated in a script and can change frequently. It would be nice to have a feature to pass the epoch through a command line flag, or at least pass the whole action.yml file as a string to the curator command line.

**Comment by untergeek** [comment]
That's an interesting use of `epoch`.  It was included primarily for testing.  It was always intended that Curator use time relative to the time of execution to determine which indices are actionable, rather than absolute time.  This is evident that even with the `epoch` option, you are still obligated to use those relative timings, e.g. older than 1 second.

In any case, this feature described in this ticket should otherwise be added to #697

**Comment by jbwl** [comment]
Thank you for considering it!
