### ISSUE TITLE
curator error 

### ISSUE THREAD

**Issue by elJoeyJojo** [elastic/curator#739]
I have an ELK server that I need to clear logs for every 10 days but curator keeps giving me this error when I run it:

Traceback (most recent call last):
  File "/usr/bin/curator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: elasticsearch>=0.4.4,<1.0.0

And this is my ElasticSearch info:

DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
---
Metadata-Version: 2.0
Name: elasticsearch
Version: 0.4.5
Summary: Python client for Elasticsearch
Home-page: https://github.com/elasticsearch/elasticsearch-py
Author: Honza Král
Author-email: honza.kral@gmail.com
Installer: pip
License: Apache License, Version 2.0
Location: /usr/lib/python2.6/site-packages
Requires: urllib3
Classifiers:
  Development Status :: 4 - Beta
  License :: OSI Approved :: Apache Software License
  Intended Audience :: Developers
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 3
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy

Do I have to upgrade to Python 2.7? 

Thanks for all your help

**Comment by untergeek** [comment]
Whoa!  That's some old stuff there.  Curator has not used those versions in a _very_ long time.  Curator is now on version 4.0.6, and has some very different configuration options than you are probably seeing.  

> Name: elasticsearch
> Version: 0.4.5

The current version of the Elasticsearch python module is 2.4.0.  If you're using a version of Curator old enough to depend on something that old, you are definitely running an outdated version of Curator.

As far as the `DistributionNotFound` error is concerned, there is a FAQ answer for that [here](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/entrypoint-fix.html) in the official documentation.

I haven't seen the Python 2.6 deprecation notice before today, but it makes sense that you would need to upgrade to 3.5 or 2.7 if you want to be on a supported level.  Otherwise, I will do my best to continue to support 2.6 via the RPM/DEB packages described [in the documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/installation.html).

**Comment by elJoeyJojo** [comment]
@untergeek i just installed Elasticsearch so how is it that it's so old? How can I upgrade to Elasticsearch Python Module 2.4.0 ? it is really just for testing to see how it goes so I am not too concerned about losing log info in there. Btw, thanks for your help

**Comment by untergeek** [comment]
@elJoeyJojo Elasticsearch the java application and elasticsearch the python module are different from each other.  One is the search engine, the other is the python client library.  

How you upgrade the python module depends on how it was installed.  How did you install it on your system?

**Comment by elJoeyJojo** [comment]
I installed ELK based on Digital Ocean's KB https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-1-7-logstash-1-5-and-kibana-4-1-elk-stack-on-centos-7 and all I did was install curator by installing python-pip and then elasticsearch-curator on this CentOS VM

I will admit, I am not a Linux Admin, seemed like a cool thing to check out and I like it but the logs are filling up too quickly and I can't add disk space so I thought curator could help get rid of old logs but creating a cronjob

**Comment by untergeek** [comment]
Current release versions are:

Elasticsearch: 2.3.5
Logstash: 2.3.4
Kibana: 4.5.4
Logstash forwarder is deprecated in favor of [filebeat](https://www.elastic.co/products/beats/filebeat)

It seems that the tutorial is nearly 1 year old.  The Elastic stack is growing very quickly.

If you truly installed python-pip and did `pip install elasticsearch-curator`, I'd be curious to know what version it was.

Please paste the output of `pip list | grep elastic`

**Comment by elJoeyJojo** [comment]
@untergeek looks like it was 0.4.5

elasticsearch (0.4.5)
elasticsearch-curator (0.6.2)

**Comment by untergeek** [comment]
And you installed via `pip install elasticsearch-curator`?  That suggests that DigitalOcean has its own mirror of pip, and it's very behind.

Please paste the output of `pip install -U elasticsearch elasticsearch-curator`

**Comment by elJoeyJojo** [comment]
k I upgraded them

elasticsearch (2.4.0)
elasticsearch-curator (4.0.6)

however after i run /usr/bin/curator i keep getting the same errors, all i am trying to do is run this:

$ /usr/bin/curator --host localhost delete --older-than 10

**Comment by untergeek** [comment]
That's the syntax for a _very_ old version of Curator (2.x, I think).  The 3.x syntax was different from that, and the 4.x syntax uses YAML configuration files.

If you want command-line syntax for Curator, you will need to do `pip install -U elasticsearch-curator==3.5.1` to go _back_ to that version.

After that, you'll need to run:

```
curator --host localhost delete indices --timestring '%Y.%m.%d' --older-than 10 --time-unit days
```

See: https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/time-unit.html

Other than that, the documentation is all online.  Please refer to current documentation instead of older, unreliable information on blog posts.  The documentation for the most recent versions is at https://www.elastic.co/guide/en/elasticsearch/client/curator/index.html

**Comment by elJoeyJojo** [comment]
mmm... i can't even run curator --help 
same error but the elasticsearch and curator seems to be up to date
i get the same error, tried rebooting it

**Comment by untergeek** [comment]
Did you not follow the instructions in my first comment to fix the DistributionNotFound error?

https://www.elastic.co/guide/en/elasticsearch/client/curator/4.0/entrypoint-fix.html (same fix for any version of Curator)

**Comment by elJoeyJojo** [comment]
sorry about that, i totally missed that! thanks @untergeek

**Comment by untergeek** [comment]
You're welcome.
