### ISSUE TITLE
Curator 4.1.2 ignoring use_ssl and forcing HTTPS connection

### ISSUE THREAD

**Issue by jayant-biz4** [elastic/curator#782]
Facing a weird issue. Curator is always trying to create HTTPS connection irrespective of the use_ssl setting.

Config File:

`client:
  hosts:
    - localhost
  port:
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key: XXXXXXXXXXXXXXXXX
  aws_secret_key: 9XXXXXXXXXXXXXXXXXX
  aws_region: us-east-1
  ssl_no_validate: True
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: DEBUG
  logfile:
  logformat: default
  blacklist: ['elasticsearch']`

The relevant portion of log output is:

`2016-10-13 02:03:41,692 DEBUG              curator.utils             get_client:524  kwargs = {'aws_secret_key': 'XXXXX', 'url_prefix': '', 'http_auth': None, 'certificate': None, 'aws_key': 'XXXXXXX', 'aws_region': 'us-east-1', 'client_cert': None, 'hosts': ['localhost'], 'timeout': 21600, 'use_ssl': False, 'master_only': False, 'port': 9200, 'ssl_no_validate': True, 'client_key': None}
2016-10-13 02:03:41,698 INFO      urllib3.connectionpool              _new_conn:664  Starting new HTTPS connection (1): localhost
2016-10-13 02:03:41,715 INFO      urllib3.connectionpool              _new_conn:664  Starting new HTTPS connection (2): localhost
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 9, in <module>
    load_entry_point('elasticsearch-curator==4.1.2', 'console_scripts', 'curator')()
  File "/usr/local/lib/python2.7/site-packages/curator/curator.py", line 5, in main
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/curator/cli.py", line 165, in cli
    client = get_client(**client_args)
  File "/usr/local/lib/python2.7/site-packages/curator/utils.py", line 587, in get_client
    'Error: {0}'.format(e)
elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: ConnectionError(HTTPSConnectionPool(host='localhost', port=9200): Max retries exceeded with url: / (Caused by <class 'httplib.CannotSendRequest'>: )) caused by: ConnectionError(HTTPSConnectionPool(host='localhost', port=9200): Max retries exceeded with url: / (Caused by <class 'httplib.CannotSendRequest'>: ))`

Any ideas what could be causing this?

thanks
Jayant

**Comment by untergeek** [comment]
I'm kind of confused that you are trying to connect to localhost in your configuration file, but are using AWS IAM credentials.  I will address each of the scenarios I can conceive of, based on what I'm seeing.

## IAM Credentials and AWS ES
The first thing you should know, before you go any farther, is that Curator 4 does not work with AWS ES and IAM credentials: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/faq_aws_iam.html

They remain as place-holders in case Amazon AWS ES ever allows the cluster state metadata endpoint in the future.


The main reason for your observation is at https://github.com/elastic/curator/blob/v4.1.2/curator/utils.py#L558

The override only happens if the AWS IAM key, secret key and region (all three) are set. If you're connecting with IAM credentials, it forces use_ssl to True, because that's how those work, and that is required.  That's why it is forcing SSL, even though you haven't set that.

## Elasticsearch on own EC2 instances
If you are using your own Elasticsearch nodes in your own AWS EC2 instances, then you do not need IAM credentials, and they won't work for you in this case anyway.  Don't populate those fields in the configuration YAML file if this is the case.

**Comment by jayant-biz4** [comment]
Thanks for your help. The scenario is the second scenario. I was little confused I guess. Those were  keys for S3 storage as the snapshot is being stored on S3. Did not realize that those keys are stored as part of snapshot repository itself.

I have removed the keys from the configuration file and everything is working now.
