### ISSUE TITLE
Snapshot name with timestamp always uses UTC

### ISSUE THREAD

**Issue by soenkeliebau** [elastic/curator#797]
I am using curator to create a daily snapshot of some indices and use the following action definiton for this:

```javascript
actions:
 1:
    action: snapshot
    description: Snapshot everything beginning with analytics- 
    options:
      repository: backup_server
      name: 'analytics-%Y%m%d%H%M%S'
      ignore_unavailable: False
      include_global_state: True
      partial: False
      wait_for_completion: True
      skip_repo_fs_check: False
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: analytics-
      exclude:
```

When I test this a snapshot is created, however the timestring used for the snapshot name is in UTC, while the server timezone is UTC+2. So for example when I run curator at 13:00 local time, the snapshot will be created with a timestring of "110000", not adjusted for the servers timezone.

I couldn't find any setting to change this behavior, but maybe I am missing something here. From looking at the [code](https://github.com/elastic/curator/blob/master/curator/utils.py#L1013):
```
 rendered += str(datetime.utcnow().strftime('%{0}'.format(curr)))
```
I get the impression that UTC is simply assumed, though I am not a python guy and won't pretend that I understood everything that is happening.

I think it would be useful to change this to adjust for the timezone configured on the server, or introduce an optional parameter to pass in a timezone to use. 
It would probably be good to also be able to add timezone information to the snapshot name in this case to avoid confusion.

**Comment by untergeek** [comment]
It's a fair question.  The reason everything is in UTC is because internal to Elasticsearch, everything is in UTC.  The snapshot metadata and index creation date are in epoch format, which is UTC.  Logstash pushing year/month/day index names does rollover at UTC 0:00.  Another reason is that snapshot names have a narrow list of what's acceptable, and adding a timezone information would result in being human readable, but not easily re-parsed back, as only lower-case letters and limited punctuation are allowed in snapshot names.

Curator now does everything in UTC as well.  It would introduce a lot of complexity to handle timezones.  I would have to do it for everything in Curator, and I'm not sure that's something I want to pursue.  This is admittedly in part because it will be a lot of support work trying to answer questions about time zone support, native time zones, people who have things start breaking because they did some weird hack to get around this, etc.  It's been both convenient and predictable to keep things at UTC, as it's not unfamiliar to users of Curator.

I understand it's inconvenient to have to reckon against UTC, but I don't plan on changing this.  If someone wanted to undertake the monumental task of adding timezone support, not just for a narrow use case but across the board, I would probably merge it.  I'm not anticipating that happening, though.

**Comment by soenkeliebau** [comment]
Ok, fair enough. It is not an issue anyway, more of a minor nuisance. Thanks for the quick response.

I'll close the issue.
