### ISSUE TITLE
elasticsearch version 5.0 support

### ISSUE THREAD

**Issue by subbu-sw** [elastic/curator#824]
From the curator github main page, we see that the elasticsearch versions 2.0 through 5.0 is supported by curator 4. However in version 4.2.0, there is an elasticsearch-py version lock introduced (http://curator.readthedocs.io/en/latest/Changelog.html) that basically makes curator not work with elasticsearch 5.0.

Is there a version that supports elasticseach 5.0, or expected shortly?

**Comment by untergeek** [comment]
If you look at the compatibility matrix, you'll see that Elasticsearch 5.0 is fully supported with all current actions and filters. The elasticsearch-py module, version 2.4, supports all necessary API calls to allow Curator to work with Elasticsearch versions 2.0 through 5.0. 

The python module version shift you saw is because version 5.0 of the python module has some API changes that caused integration tests to fail. When Curator v5 comes out it will be refactored to use the v5 python module.
