### ISSUE TITLE
Question: why does singleton-cli not support alias and restore?

### ISSUE THREAD

**Issue by alexef** [elastic/curator#851]
Is this not yet implemented (due to lack of resources) or is it intentionally avoided?

We would really benefit of using snapshot restore without a config file.

**Comment by untergeek** [comment]
Alias is avoided because it's very different and a terrific pain to try to accurately create the add and remove filter blocks as JSON on the command-line.  Sure, it could be done if someone _really_ wanted to do it, mostly because the schema checking would validate the options.  It still makes for a _very_ ugly command line, that's for sure.

Restore is not implemented because it also is a pain with so many flags and options.  I'd happily merge a restore action if someone wanted to put it in and manually test it.

**Comment by shortdudey123** [comment]
@untergeek how do you propose doing dynamic alias creation without the CLI?  i.e. creating monthly aliases on daily indexes. With Curator 3 you could do a bash script and get date info from bash commands but with the YAML config, its not dynamic.

**Comment by untergeek** [comment]
Curator 4 supports environment variables.  You could still have a script that generates them, then calls Curator.

**Comment by untergeek** [comment]
The new [period filter](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.0/filtertype_period.html) will help with the alias issue.

**Comment by untergeek** [comment]
Alias was added in #1214.
