### ISSUE TITLE
Python strptime cannot use hour value of 24 for '%H'

### ISSUE THREAD

**Issue by Joelp** [elastic/curator#869]
Hi, using curator for delete indices. But in one type of indices it returns error:
Failed to complete action: delete_indices.  <class 'ValueError'>: unconverted data remains: 4

**My indices are like:**
filebeat-2017.01.19.04
filebeat-2017.01.18.20
filebeat-2017.01.18.23
filebeat-2017.01.19.05
filebeat-2017.01.20.02
filebeat-2017.01.17.16

**Curator action file:**
actions:
  1:
    action: delete_indices
    description: Delete indices older than 3 days (filebeat-*)
    options:
      ignore_empty_list: true
      timeout_override:
      continue_if_exception: false
      disable_action: false
    filters:
      - filtertype: pattern
        kind: prefix
        value: filebeat-
        exclude:
      - filtertype: age
        source: name
        direction: older
        timestring: '%Y.%m.%d.%H'
        unit: days
        unit_count: 3
        exclude:

My curator version is 4.2.5

What am I doing wrong?

**Comment by untergeek** [comment]
Without running with loglevel set to DEBUG, and attaching a sanitized version of the output (i.e. no passwords or public IPs), I will have a very hard time debugging or helping find the root cause. 

If I had to guess, though, I suspect you may have an index that starts with filebeat but somehow has an atypical value for the timestring.

**Comment by Joelp** [comment]
I tried to another string format, but same result.

this command works OK:
curl -XDELETE '<server ip>:<server port>/filebeat-2017.01.17.17'

see curator dry-run debug log:
[curator.log.zip](https://github.com/elastic/curator/files/723027/curator.log.zip)

**Comment by untergeek** [comment]
Sorry for the long wait.  I've been dealing with a kidney stone and am just getting back to things.

I did some digging, and the long and short of it is that Python will not let you use hours in a timestring to extract a timestamp. I know, it was a huge surprise to me, and I'll be having to document this.  You're the first to report it (lucky you, right?).

I had used a hacky way of getting around this in the Curator 2.x and 3.x era. However, this is no longer a recommended approach, since a much better way of calculating age now exists in Elasticsearch.

You can still use this timestring with `%H` hours to filter indices like this:
```
- filtertype: pattern
  kind: timestring
  value: '%Y.%m.%d.%H'
```
Since you cannot use this timestring to calculate age, I recommend using [`source: creation_date`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_creation_date), or if you've been ingesting old data and the creation date would be inaccurate, the most accurate is 
 [`source: field_stats`](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/fe_source.html#_field_stats).  

`creation_date` is simply the epoch timestamp recorded at the time the index was created.  With time-series data this is usually accurate, but it can be inaccurate if you've ingested some old syslog line, and Logstash creates an index for `2017.01.01` on the 20th of the month. Based on the _content_ of the log line, Logstash makes the index name's date in the past, but the `creation_date` would still be `2017.01.20`.  To avoid scenarios like this, use `source: field_stats` to calculate index age.

The `field_stats` API in Elasticsearch will tell you what the min and max values of a field are in an Elasticsearch index.  For Curator, presuming you're using the `@timestamp` field, the configuration might look like:

```
# '@timestamp' is the default value for 'field', so the 'field' line can be omitted if that is the case
# 'min_value' is the default for 'stats_result', so the 'stats_result' line can be omitted if that is the case
- filtertype: age
  source: field_stats
  field: '@timestamp'
  stats_result: min_value 
  direction: older
  unit: days
  unit_count: 3
```
This will calculate an index's age based on the minimum value found for `@timestamp` in the index.  If that is older than 3 days ago, it will remain in the actionable list.  

You could also use `max_value` for `stats_result`, which would calculate index age based on the "newest" value in the index.  It is important to remember that for time calculation, `min_value` and `max_value` are going to be evaluating epoch time.  As such, a bigger value indicates a more recent time stamp.

**Comment by untergeek** [comment]
For the record, this is what happens:
```
>>> import datetime
>>> index_timestamp = '2017.01.22.24'
>>> timestring = '%Y.%m.%d.%H'
>>> datetime.datetime.strptime(index_timestamp, timestring)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 4
```
If I set the hour to 23, it works just fine:
```
>>> i_t = '2017.01.22.23'
>>> ts = '%Y.%m.%d.%H'
>>> datetime.datetime.strptime(i_t, ts)
datetime.datetime(2017, 1, 22, 23, 0)
```

**Comment by untergeek** [comment]
Did you use `%H` in your filebeat.yml file? Or `%k`?  See https://godoc.org/github.com/elastic/beats/libbeat/common/dtfmt

**Comment by Joelp** [comment]
Thanks a lot for reply and exhaustive explanation :)

Somewhere I read that I can't use H in Logstash. But as I see in example here https://www.elastic.co/guide/en/logstash/5.2/event-dependent-configuration.html , I can.

So I think that best way for me is use this index format (in logstash):

`index => "filebeat-%{+YYYY.MM.dd.HH}"` instead of
`index => "filebeat-%{+YYYY.MM.dd.kk}"`

**Comment by untergeek** [comment]
Yes, `%H` is usable in Logstash. It always has been, but there you would use 2 H's to indicate 2 digits, just like you have in your example.

**Comment by untergeek** [comment]
I'm going to mark this as closed.

**Comment by ypid-geberit** [comment]
I just hit this issue because for testing I created an index with a not existing date (month to be precise):

```
2020-06-18 14:37:57,168 DEBUG              curator.utils         get_date_regex:200  regex = \d{4}\.\d{2}\.\d{2}
2020-06-18 14:37:57,168 DEBUG          curator.indexlist           working_list:237  Generating working list of indices
2020-06-18 14:37:57,170 ERROR                curator.cli                    run:213  Failed to complete action: delete_indices.  <class 'ValueError'>: unconverted data remains: 3
```

I don’t like the idea that Curator just stops when it hits an invalid date. I think it would be more robust to log this index as a warning, skip it and move on.

Can you maybe reopen this?

**Comment by untergeek** [comment]
Hi, @ypid-geberit 

What you're asking for—a proper error for an invalid date—is not covered by this issue. Please raise a new issue and we can have a discussion about it there.

**Comment by ypid-geberit** [comment]
Hi @untergeek

Misjudgment of my side then whether or not I should have created a new one. I created a new issue #1545 now. That is cleaner. You are right.
