### ISSUE TITLE
Filter snapshots based on duration

### ISSUE THREAD

**Issue by JD557** [elastic/curator#878]
It would be nice to be able to filter snapshots based on duration, so that crashed snapshots (e.g. `state = IN_PROGRESS && duration > 24h`) could be cancelled automatically.

**Comment by untergeek** [comment]
That's not a common occurrence. If you have a snapshot running for over 24 hours, chances are good one of these is true:

1. **You are running a _very_ large snapshot (i.e. terabytes of data in one shot)**  This can be a problem because segment merges are affected while a snapshot is running.  It's perhaps better to take smaller chunks of indices to avoid super-long snapshot run times.
2. **You have a huge number of snapshots in your repository.** Elasticsearch has to compare your current indices/segments to compare them with what's already stored so as not to duplicate segments.  This can be time consuming.  Ways around this include performing forceMerges on older time series data _before_ snapshotting so the segment count is less.
3. **Your cluster is under some duress.**  This could be from any number of causes.  

In any case, there _is_ a filter that can detect the state of snapshots: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_state.html

This could be used as your filter with the `curator_cli` binary and the `show_snapshots` action to keep tabs on snapshots from the command-line.  I do not recall offhand whether the snapshot start date was included in the verbose output, but I do not think I did.  That could be added, potentially.

**Comment by untergeek** [comment]
Closing this as I do not feel it is a necessary feature.  Feel free to reopen and start the discussion again if you feel that it should be.
