### ISSUE TITLE
Delete the indices only if it is close? 

### ISSUE THREAD

**Issue by amritfd** [elastic/curator#905]
In production if some one pass a wrong index , or it filter a wrong index while doing delete then it will be gone. Management might not be ready to take that risk. What if we add a feature like delete indices only if it is closed? It might be useful who want to close the indices and then remove it to be on a safe side. 

I am aware of `dry-run`

**Comment by untergeek** [comment]
This feature is as simple as adding the [`opened` filtertype](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_opened.html) :

```
- filtertype: opened
  exclude: True
```

This will exclude all open indices.  You can even test this at the command line with the `curator_cli` command, like this:

```
$ curator_cli show_indices --filter_list '{"filtertype":"opened", "exclude":true}'
logstash-2017.03.01
metricbeat-2017.03.01
```
Note that this command only runs without extra flags if you have a properly configured `curator.yml` file in the executing user's home directory in a `.curator` subdirectory, i.e. `$HOME/.curator/curator.yml`.

Since this feature is already available, I'm closing this issue.
