### ISSUE TITLE
Curator version matrix incorrect

### ISSUE THREAD

**Issue by shortdudey123** [elastic/curator#959]
See https://www.elastic.co/guide/en/elasticsearch/client/curator/current/version-compatibility.html

The matrix shows curator version 4.x being compatible with 5.x.  Per https://github.com/elastic/curator/issues/885 this is not the case.  4.x curator is compatible with <= 5.1.99

5.2.0+ support was not added until curator version 5
See https://github.com/elastic/curator/commit/53ce25ecc7b27fb61f1ab581b8023e0dcb81a4f4#diff-cf1a61947b41b730a5aa8535dbd5979fR6

**Comment by untergeek** [comment]
This is an unfortunate side effect of waiting for each minor version to come out before updating the compatibility—a practice I gave up on after one too many complaint.

4.x Curator _is_ compatible with Elasticsearch 5.x, so long as you are running anything 4.2.6 or later (4.3.1 is the most recent of the 4.x branch).

There's also no reason to run Curator 4.x if you're running Elasticsearch 5.x, especially with the new features added in Curator 5.

**Comment by shortdudey123** [comment]
`4.2.6` is the newest `4.x` release per the [changelog](https://github.com/elastic/curator/blob/39a6e9ba84638f5e54ae863c84874a240cdf4959/docs/Changelog.rst) which does not include a mention of the ES version changes, but i do see it in the code for `4.2.6`

**Comment by untergeek** [comment]
There was a split for the 5.x branch, and 5.x now trails master, while 4.x is managed separately.

You should be looking at the [4.x branch Changelog](https://github.com/elastic/curator/blob/4.x/docs/Changelog.rst), or at the [official documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/4.3/versions.html), which shows all of the documentation changes for minor releases since 3.3 by way of a drop-down.  

Again, I apologize for the inconvenience, but I got in the habit of tracking the most recent version I could trust until I updated tests for Travis.  Please understand the difficulties of spanning major versions by using an _older_ version of the python API (2.4.1).  I didn't want to have anything break.  I was nervous about future code-arounds biting users.  Instead, I had them unable to use new versions of ES until I had updated Curator.  However, once I had integration testing with _all_ current releases of all minor branches of Elasticsearch, I felt safe to put a blanket support for all 5.x versions.  Before that, Curator 4 supported ES 5 _insofar as you had the most recent version of Curator._  

This is why, with Curator 5, I opted to forgo any sort of reverse compatibility, so I wouldn't have to do that again.

See [4.0.0](https://github.com/elastic/curator/blob/v4.0.0/curator/settings.py), [4.1.0](https://github.com/elastic/curator/blob/v4.1.0/curator/defaults/settings.py#L7), [4.2.0](https://github.com/elastic/curator/blob/v4.2.0/curator/defaults/settings.py#L7), [4.2.3](https://github.com/elastic/curator/blob/v4.2.3/curator/defaults/settings.py#L6), [4.2.4](https://github.com/elastic/curator/blob/v4.2.4/curator/defaults/settings.py#L6), [4.2.6](https://github.com/elastic/curator/blob/v4.2.6/curator/defaults/settings.py#L6).

As stated, now I track all new versions in Travis: [4.2.6](https://github.com/elastic/curator/blob/v4.2.6/.travis.yml#L9-L15), [4.3.1](https://github.com/elastic/curator/blob/v4.3.1/.travis.yml#L10-L19), [5.0.2](https://github.com/elastic/curator/blob/v5.0.2/.travis.yml#L10-L14).

I apologize again for the inconvenience, but there's nothing I will be changing, since the most recent version of Curator 4 works just fine with ES 5.x.
