### ISSUE TITLE
IndexList _get_metadata consumes excessive amount of memory

### ISSUE THREAD

**Issue by brandond** [elastic/curator#968]
I've got an ES cluster maintaining 32 days of LogStash data in open indexes, and another 60 in closed indexes. I'm using the standard LogStash index naming scheme.

My issue is that running a Delete action can cause Python to consume several gigs of memory, presumably because it's pulling down and storing in memory metadata for all of the indexes, which is (due to the sheer number of mappings in each index) is quite large - about 110MB of JSON, without pretty-printing enabled.

Here's what I see if I profile `IndexList._get_metadata` with memory_profiler:

```
Filename: /home/ec2-user/ansible-env/lib/python2.7/site-packages/curator/indexlist.py

Line #    Mem usage    Increment   Line Contents
================================================
   143     34.4 MiB      0.0 MiB       @profile
   144                                 def _get_metadata(self):
   145                                     """
   146                                     Populate `index_info` with index `size_in_bytes` and doc count
   147                                     information for each index.
   148                                     """
   149     34.4 MiB      0.0 MiB           self.loggit.debug('Getting index metadata')
   150     34.4 MiB      0.0 MiB           self.empty_list_check()
   151     34.4 MiB      0.0 MiB           index_lists = chunk_index_list(self.indices)
   152   1463.6 MiB   1429.3 MiB           for l in index_lists:
   153                                         working_list = (
   154     34.4 MiB  -1429.3 MiB                   self.client.cluster.state(
   155   1463.6 MiB   1429.3 MiB                       index=to_csv(l),metric='metadata'
   156   1463.6 MiB      0.0 MiB                   )['metadata']['indices']
   157                                         )
   158   1463.6 MiB      0.0 MiB               if working_list:
   159   1463.6 MiB      0.0 MiB                   for index in list(working_list.keys()):
   160   1463.6 MiB      0.0 MiB                       s = self.index_info[index]
   161   1463.6 MiB      0.0 MiB                       wl = working_list[index]
   162   1463.6 MiB      0.0 MiB                       if not 'creation_date' in wl['settings']['index']:
   163                                                     self.loggit.warn(
   164                                                         'Index: {0} has no "creation_date"! This implies '
   165                                                         'that the index predates Elasticsearch v1.4. For '
   166                                                         'safety, this index will be removed from the '
   167                                                         'actionable list.'.format(index)
   168                                                     )
   169                                                     self.__not_actionable(index)
   170                                                 else:
   171                                                     s['age']['creation_date'] = (
   172   1463.6 MiB      0.0 MiB                               fix_epoch(wl['settings']['index']['creation_date'])
   173                                                     )
   174                                                 s['number_of_replicas'] = (
   175   1463.6 MiB      0.0 MiB                           wl['settings']['index']['number_of_replicas']
   176                                                 )
   177                                                 s['number_of_shards'] = (
   178   1463.6 MiB      0.0 MiB                           wl['settings']['index']['number_of_shards']
   179                                                 )
   180   1463.6 MiB      0.0 MiB                       s['state'] = wl['state']
   181   1463.6 MiB      0.0 MiB                       if 'routing' in wl['settings']['index']:
   182                                                     s['routing'] = wl['settings']['index']['routing']
```

An easy fix for this is to reduce the chunk size returned by `chunk_index_list` - if I reduce the max length from 3072 to 64 characters, it takes a few more round-trips to collect the data, but memory never grows out of control:

```
Filename: /home/ec2-user/ansible-env/lib/python2.7/site-packages/curator/indexlist.py

Line #    Mem usage    Increment   Line Contents
================================================
   143     34.4 MiB      0.0 MiB       @profile
   144                                 def _get_metadata(self):
   145                                     """
   146                                     Populate `index_info` with index `size_in_bytes` and doc count
   147                                     information for each index.
   148                                     """
   149     34.4 MiB      0.0 MiB           self.loggit.debug('Getting index metadata')
   150     34.4 MiB      0.0 MiB           self.empty_list_check()
   151     34.4 MiB      0.0 MiB           index_lists = chunk_index_list(self.indices)
   152    159.3 MiB    124.9 MiB           for l in index_lists:
   153                                         working_list = (
   154    159.3 MiB      0.0 MiB                   self.client.cluster.state(
   155    197.5 MiB     38.2 MiB                       index=to_csv(l),metric='metadata'
   156    182.3 MiB    -15.2 MiB                   )['metadata']['indices']
   157                                         )
   158    182.3 MiB      0.0 MiB               if working_list:
   159    182.3 MiB      0.0 MiB                   for index in list(working_list.keys()):
   160    182.3 MiB      0.0 MiB                       s = self.index_info[index]
   161    159.3 MiB    -23.0 MiB                       wl = working_list[index]
   162    159.3 MiB      0.0 MiB                       if not 'creation_date' in wl['settings']['index']:
   163                                                     self.loggit.warn(
   164                                                         'Index: {0} has no "creation_date"! This implies '
   165                                                         'that the index predates Elasticsearch v1.4. For '
   166                                                         'safety, this index will be removed from the '
   167                                                         'actionable list.'.format(index)
   168                                                     )
   169                                                     self.__not_actionable(index)
   170                                                 else:
   171                                                     s['age']['creation_date'] = (
   172    159.3 MiB      0.0 MiB                               fix_epoch(wl['settings']['index']['creation_date'])
   173                                                     )
   174                                                 s['number_of_replicas'] = (
   175    159.3 MiB      0.0 MiB                           wl['settings']['index']['number_of_replicas']
   176                                                 )
   177                                                 s['number_of_shards'] = (
   178    159.3 MiB      0.0 MiB                           wl['settings']['index']['number_of_shards']
   179                                                 )
   180    159.3 MiB      0.0 MiB                       s['state'] = wl['state']
   181    159.3 MiB      0.0 MiB                       if 'routing' in wl['settings']['index']:
   182                                                     s['routing'] = wl['settings']['index']['routing']
```

**Comment by untergeek** [comment]
I'm sorry you've had a bad experience.  You are, indeed, hitting something I never foresaw happening.

Is the box running Curator a very small machine?  Is that why 1.5G is a constraining factor?  Curator isn't obliged to run on the same machine as Elasticsearch itself, or even in the same subnet.  It only requires access to the REST endpoint of one of the nodes in the cluster.  This means you could have a larger machine run Curator without it requiring a larger machine.

I mention this, because while it is possible to alter the chunk size, I hesitate to do so.  Allow me to explain my reasoning.

First off, mappings that large per index are discouraged.  Indeed, if you have multiple `_type` values per index, that will pose a problem for future upgrading as the concept of `_type` has been removed for Elasticsearch 6.0.  In the future, Elasticsearch will only support one "type" (without using that terminology), or mapping per index.  This simplification will yield a tremendous benefit for indexing and searching performance, as well as index compression and storage density.  Consequently, giant mappings will be much more rare.  What I'm trying to gently suggest here is that your use of large mappings–and presumably multiple types–is not ideal and is likely to be a contributing factor, and that Elasticsearch developers have been working for a long time to gradually constrain such things as they lead to undesirable outcomes and performance issues.

The `chunk_index_list` function's primary function is to prevent the initial URL from being too large for Elasticsearch.  By default, the initial URL cannot be more than 4000 characters long.  Since Elasticsearch allows for providing a comma-separated list of indices to act on, the chunking function is there to prevent that default limit from being hit.  It apparently can also be used to limit the number of indices in a call, as you pointed out, but this was not its original intent.

Reducing the chunk size will increase the number of round-trips necessary to complete actions.  It is a tremendous benefit to be able to have Elasticsearch finish a batch of deletes in fewer passes.  A blanket change to the `chunk_index_list` function would affect the outbound requests, not just the one reading in the metadata–which, as I understand it, is where your problem lies.

A change to the `chunk_index_list` function to allow it to be selectable at call time is _technically_ a breaking API change, which are usually reserved for major releases.  While I feel like I could ethically change it in a minor point version, that isn't the difficult part.  The difficult part is deciding whether to make chunk size definable in a configuration file, or to arbitrarily set it to some low number at just this ingestion point, which helps you, but slows things down for other users and adds to the load of the cluster—which is a valid point with large mappings, as the cluster still has to isolate all of the metadata for only the requested indices.

As an afterthought, this issue is somewhat related to #795, and may be addressed in part by any changes made in the system to address this.

At any rate, I _am_ still considering this.  These are my reasons for being hesitant to change things.

**Comment by brandond** [comment]
1.5GB isn't a specific constraint; this was just a test run. I've seen it easily get up to 3GB on slightly larger clusters. My intent was to push out curator to all the ES nodes and use the master-only flag to have it only execute daily cleanups on a single node. Unfortunately, this bug means that curator uses so much memory that it frequently ends up either hanging or OOM killing the master node, since they're running in EC2 with no swap, and ElasticSearch is configured to use the majority of memory on the host - there's not enough RAM left for a multi-GB Python process.

These indexes are primarily storing data from AWS CloudTrail, which contains audit logs for API calls to AWS services. Since many different API calls use similar parameter names with different value types, I was having trouble with mapping templates getting the fields wrong. The same parameter may look like a float for one API, a date string for another, and a complex type for a third. In order to work around this, Logstash's ElasticSearch output sets:
```
    else if [type] == "CloudTrail" {
        elasticsearch {
            document_id => "%{eventID}"
            document_type => "%{eventType}-%{eventName}"
            template => "/etc/logstash/template.json"
            template_name => "logstash"
            template_overwrite => "true"
        }
```
This results in a unique type for each API call so that I don't end up with mapping conflicts. Are you saying that this would no longer work in ES6? How will it handle multiple document schemas within the same index, when different documents might contain varying types for a given field?

**Comment by untergeek** [comment]
> This results in a unique document_type for each API call so that I don't end up with mapping conflicts. Are you saying that this would no longer work in ES6?

[Yes](https://github.com/elastic/elasticsearch/pull/24428).

> How will it handle multiple document schemas within the same index, when different documents might contain varying types for a given field?

It won't.  You will have to create multiple indices with one mapping in each.  Perhaps that will be one index-type per API, so that the fields match.  It will require rethinking your indices and retention approach.

> Unfortunately, this bug means that curator uses so much memory that it frequently ends up either hanging
While I appreciate that the current behavior is not what you'd like, the constraints you've placed on your nodes makes this seem more like a self-imposed difficulty than a bug.  Any process will hang when a system is starved for memory, and Curator is no exception.

> or OOM killing the master node, since they're running in EC2 with no swap, and ElasticSearch is configured to use the majority of memory on the host 
By your own admission here your nodes are not running with 1/2 the system memory dedicated to Elasticsearch (leaving the other half behind to act as filesystem caching) [per Elastic's official recommendations](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/heap-size.html). If 3G of sudden RAM consumption can bring down an Elasticsearch node, you haven't left any room for anything else.  While it is possible to alter Curator to make it possible for you to keep doing this, the configuration described for your cluster nodes is not recommended.  Curator has behaved well in clusters that meet those recommendations.

While I am not ruling out making an adjustment to help you, the assumption that this behavior is unwarranted in all cases (which would be an actual bug) is incorrect.

**Comment by untergeek** [comment]
I did some character counting.  The chunk size of 3072 breaks up the index list into comma-separated list of indices. Each index of the pattern `logstash-YYYY.MM.dd` is 21 characters.  

With a chunk size of 64, Curator would be forced to make a separate call for every four indices in the cluster, as the character length for 4 indices would be 84 characters (that's the first time in the loop it would be bigger than 64).

With your 92 index cluster (not including any of the other system indices), that results in 23 round-trip calls to the cluster to get the metadata.  This is not a no-op for the cluster.  It is taxing for Elasticsearch to read ALL of the cluster metadata, then parse out the metadata for only the indices specified in the call, and return that value.  It's taxing enough to make one giant call for as many indices as you can fit in a single call (which was the reason to change to this behavior in Curator 4).

**Comment by untergeek** [comment]
After pondering on this for some time, I will not be changing this part of the code.  There may be some memory optimizations I can perform, but this is not going to be one of them.
