### ISSUE TITLE
Correct Curator version mismatch error reporting

### ISSUE THREAD

**Issue by Nodens2k** [elastic/curator#992]
Hi there,

Trying to setup this configuration I'm getting this error message:

elasticsearch.exceptions.ElasticsearchException: Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 5.4.0 incompatible with this version of Curator (5.4.0)

Is this the expected behaviour? Should I wait for a more recent version of Curator?

Thanks

**Comment by untergeek** [comment]
That error is a bit of a mistake.  Curator isn't reporting its own version in those parenthesis, [but the elasticsearch version](https://github.com/elastic/curator/blob/v5.1.1/curator/utils.py#L615-L619).  I've neglected, on multiple occasions, to correct this:

```
        raise CuratorException(
            'Elasticsearch version {0} incompatible '
            'with this version of Curator '
            '({0})'.format(".".join(map(str,version_number)), __version__)
        )
```
to be this:

```
        raise CuratorException(
            'Elasticsearch version {0} incompatible '
            'with this version of Curator '
            '({1})'.format(".".join(map(str,version_number)), __version__)
        )
```
Note the changing of `({0})` to `({1})`.  This is why it's not reporting Curator's version.

So the question is, what version of Curator are you actually using?

```
$ curator --version
```

**Comment by untergeek** [comment]
You see, there isn't yet a Curator version 5.4.  The current version is 5.1.1.

**Comment by Nodens2k** [comment]
Hi, my bad, I should have realized that. I guess I was too tired :-D

We are trying to use the latest version, so I guess it is not really compatible with ES 5.4 or 5.4.1 yet, right?

Do you have a date in mind for a new release supporting the latest ES versions?

**Comment by alexcurtin** [comment]
@untergeek Do you have a roadmap for when a version of Curator will be released thats compatible with Elastic Search vs 5.4.x?

**Comment by untergeek** [comment]
@alexcurtin You've missed the message in this issue.  Curator 5.1.1 fully supports _all_ 5.x versions of Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/version-compatibility.html

The issue here is not that Curator is incompatible, but that it's not accurately reporting the correct version of Curator.  You can find the actual version of Curator you're running by running:

```
curator --version
```

**Comment by alexcurtin** [comment]
@untergeek Thanks sorry. I bumped my curator version to 5.1.1 and I no longer see that error.

**Comment by woqer** [comment]
@untergeek is right about this lines https://github.com/elastic/curator/blob/v5.1.1/curator/utils.py#L615-L619

I also got the same missleading error message. Upgrading curator solved my problem but took me some time to realize what the problem was since the error message reported version 5.5 for curator (when that is my ES cluster version, not curator version).
