### ISSUE TITLE
New packages required for Debian 9

### ISSUE THREAD

**Issue by untergeek** [elastic/curator#998]
Debian 9 made the leap from OpenSSL 1.0 to 1.1.  Accordingly, the pre-compiled packages do not work with a plain-jane Debian 9 install:
```
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
2017-07-06 15:50:34,008 DEBUG              elasticsearch       log_request_fail:105  > None
Unable to create client connection to Elasticsearch.  Error: ConnectionError(Can't connect to HTTPS URL because the SSL module is not available.) caused by: SSLError(Can't connect to HTTPS URL because the SSL module is not available.)
debian9-pkg-test $ openssl version
OpenSSL 1.1.0f  25 May 2017
```

Preliminary tests indicate that this will require a separate package, if not an entirely different repository.  I will have to figure out the best approach.  Compiling on Debian 9 works just fine, and the resultant package works as expected, _but only with Debian 9._  The two SSL libraries are definitely mutually exclusive.

I am unaware of any way, right now, to freeze in _multiple_ versions of the SSL library, and make it choose.  Were that possible, this would be easy.

**Comment by ThorbenJ** [comment]
Are there Debian source packages available? So that one could add deb-src to sources.list.d/..; apt-get source elasticsearch-curator; and then build with dpkg-buildpackage.
I note currently there are no Debian source packages in the repository. Is there a reason to not build source packages?

To support Deb8 and Deb9 you will probably need two package indexes each pointing to one of two package versions (which could share the same pool package hierarchy).
Although I assume you already know, just in case: There is list of repository tools, maybe switching to another would make things easier? https://wiki.debian.org/DebianRepository/Setup

Also where Debian goes Ubuntu and friends will follow, so this will likely also break in an up coming release thereof.
